### ISSUE TITLE
How to add my posts with other type?

### ISSUE THREAD

**Issue by buddhists** [Phlow/feeling-responsive#1]
Hi, Phlow:
thank you for your great effort on the theme, I have forked one of your verison on my site. but I have some questions to ask you.
I find the blog menu will direct page to \_posts\design,  If I want to divided the posts into two kinds:
one is design the other is php coding, how can it do? if this can not work how to make menu blog to show content bellow of \_posts instead of \_posts\design,

thank you.

**Comment by Phlow** [comment]
To change the navigation, just open `data/navigation.yml` and put your own categories in there.

If you want to have your own categories, you have to make an additional categories page which you can link in the navigation.

To make a category archive, just open `pages/design.md` and save it under a new name. Change the **permalink** and change the loop.

fixed #1
