### ISSUE TITLE
Sorry, I'am question. about file Gemfile on repository feeling-responsive nothing, thank's...

### ISSUE THREAD

**Issue by saifulindo** [Phlow/feeling-responsive#10]

**Comment by Phlow** [comment]
Hello Muhammad!

If I understand you correctly, you are searching for the Gemfile. It's not needed, because you only need Jekyll to use *Feeling Responsive*.

If you want to add a Gemfile, use this code in the Gemfile:

    source 'https://rubygems.org'
    
    gem 'jekyll'

**Comment by saifulindo** [comment]
Hey Phlow !

Oke thanks, successfully
