### ISSUE TITLE
How do I get my logo to show on mobile?

### ISSUE THREAD

**Issue by ghost** [Phlow/feeling-responsive#100]
Where would I put a logo for it to show in the mobile view?

Kirsten

**Comment by TWiStErRob** [comment]
It should use the same resources as the desktop site.

You can shrink the browser window to trigger the xs breakpoint and check with the inspector what's  different. Or enable mobile simulation in Chrome Dev Tools.

**Comment by ghost** [comment]
Cool, thx...

**Comment by ghost** [comment]
It seems like the issue is that it's somehow creating touch-icons for me, from a default.  How do I tell it to use my own image to generate the touch icons?

**Comment by ghost** [comment]
@synedra please find a generator on the Web. @Phlow this can be closed.
