### ISSUE TITLE
jekyll serve --config _config.yml,_config_dev.yml  

### ISSUE THREAD

**Issue by Sonju** [Phlow/feeling-responsive#103]
Per instructions I ran in terminal `jekyll serve --config _config.yml,_config_dev.yml` . 
Output: `Fatal: The configuration file _config.yml could not be found.`  config.yml file exists.  

Command `jekyll serve` output:
"Configuration file: none
            Source: /Users/MiTech/my_Dev_Lyfe/Blog
       Destination: /Users/MiTech/my_Dev_Lyfe/Blog/_site
 Incremental build: disabled. Enable with --incremental
      Generating... "

`_site` file does not exists. The file was ignored in `.gitignore`.

_Update_
Is it a multiple site issue I read in this post: https://talk.jekyllrb.com/t/support-for-multiple-sites-jekyll-multisite-in-core/1678

**Comment by quangnd** [comment]
I ran this themes successfully with:
1. bundle install
2. bundle exec jekyll serve --config _config.yml,_config_dev.yml

:)

**Comment by Phlow** [comment]
@quangnd is right :)
