### ISSUE TITLE
Blog at root with /blog for permalink

### ISSUE THREAD

**Issue by twellspring** [Phlow/feeling-responsive#107]
Migrating from another theme to feeling-responsive.  I would like my blog at / similar to #84, but would like permalinks for blog posts at /blog/xxxxxxxx.html 

Can you give any suggestions on how to accomplish this?

**Comment by TWiStErRob** [comment]
Change this line in _config.yml to set the post url:

``` yaml
permalink: /blog/:year/:month/:title.html
```

and use pagination as discussed in #84 for the blog listing.

**Comment by twellspring** [comment]
Initially the proposed solution on #84 was not working for me, but `rm -rf _site` and restarting `jekyl serve` and now it does. 

The above solution gave me the /blog in the post.  Thanks
