### ISSUE TITLE
Pagination not showing most recent pages

### ISSUE THREAD

**Issue by twellspring** [Phlow/feeling-responsive#108]
Per #107 I have my blog on the home page.  At it seemed like it was working fine ... I saw posts on the home page and thought they were the newest.   I moved on to work on the navigation and adding teasers on each post.  Now my home page is showing some blog posts but not the ones I expect.

If in _config.yaml I set `paginate: 5` one post is shown ( the oldest post )
If I set `paginate: 8` then 5 posts are shown ( the oldest 5 posts )
If I set `paginate: 9` then 3 posts are shown ( the oldest 3 posts )

The archive and pages like atom.xml & sitemap.xml all show the posts correctly newest at the top of the page.   I have stopped the jekyl server and deleted _site, started up and browse with a new browser.   Same thing remains.   Any Ideas?

The changes I made to get blog posts onto my home page

_config.yaml 
`permalink: /blog/:title/`

index.html

```

---
layout: blog
title: "My Blog Title"
header:
    image_fullwidth: "mountains.jpg"
    logo: "logo.png"
permalink: "/"

---
```

I have also made changes to 
_data/authors.yml
_data/navigation.yaml
_layouts/blog.yaml ( only added the header image/logo )
_layouts/page.yaml ( only added the header image/logo ) 
_blog/archive.html (  only added the header image/logo )

example for the last 3

```
header: 
    image_fullwidth: "mountains.jpg" 
    logo: "logo.png" 
```

**Comment by twellspring** [comment]
A question.  In blog/archive.html I found 
`permalink: "blog/archive/"`    That seems different than the rest.  I would expect `permalink: "/blog/archive/"`

**Comment by TWiStErRob** [comment]
I think you need to change paginate_path, check #84 again.
