### ISSUE TITLE
How to change image in the START page

### ISSUE THREAD

**Issue by liftmybeard** [Phlow/feeling-responsive#109]
Sorry for the n00b question, I can't seem to find the file that changes the homepage image, right now I'm using the Bare Bones version and I'd like to have an image behind the logo like you have. (yours is header_unsplash_12.jpg). I've followed the documentation but I'm somewhat confused because it won't work in the _config.yml

**Comment by TWiStErRob** [comment]
[pages/pages-root-folder/index.md](https://github.com/Phlow/feeling-responsive/blob/bare-bones-version/pages/pages-root-folder/index.md) has all the image references (header and 3 widgets) in its frontmatter.

**Comment by liftmybeard** [comment]
Yes, I found it in index.md, but changing the front matter to 

```
header:
  image_fullwidth: "header_unsplash_12.jpg"
```

will not work. What am I doing wrong? I also uploaded the image to the images directory.

**Comment by Phlow** [comment]
Is your repository uptodate? I could check it.

**Comment by TWiStErRob** [comment]
The barebones version doesn't have that image (at least in the latest).
Did you regenerate the site after the change?

Also what does "will not work" mean? Is it a 404 in browser, a generation error, ...?

**Comment by Phlow** [comment]
I think, something is mixed up: On https://liftmybeard.github.io/ The HTML is looking for a https://github.com/liftmybeard/liftmybeard.github.io/tree/master/imagesheader_unsplash_12.jpg

The URL is wrong. It should be something like https://liftmybeard.github.io/images/header_unsplash_12.jpg

This image is on GitHub Pages.

**Comment by Phlow** [comment]
You're working on the master-branch

https://github.com/liftmybeard/liftmybeard.github.io/blob/master/_config.yml

You should work on the https://github.com/liftmybeard/liftmybeard.github.io/blob/gh-pages/_config.yml

**Comment by TWiStErRob** [comment]
@Phlow no, the `username.github.io` repo is special, you need to have a `master`.
Docs: https://help.github.com/articles/user-organization-and-project-pages/
Example: https://github.com/TWiStErRob/twisterrob.github.io (I only have `master`)

**Comment by TWiStErRob** [comment]
It works now. The problem was that `urlimg` is the base for all images, not a single one, fixed in https://github.com/liftmybeard/liftmybeard.github.io/commit/61634ed5446dc57061c117ea0eca9b6fc54fc8cf

**Comment by liftmybeard** [comment]
Yes I did a master because it would not load the Github Pages once forked. 

Anyways, thanks @Phlow and @TWiStErRob for your time and help. I figured out the error by inspecting it via HTML, after you correctly pointed out that I messed up with the 

`urlimg`

 in the _config.yml!

Sorry once again for the noob question!
