### ISSUE TITLE
How to center logo.png

### ISSUE THREAD

**Issue by Harold-Anderson** [Phlow/feeling-responsive#110]
My logo is sticking out the bottom of the header in the frontpage layout with a solid color as the background.  I have modified about 20 different numbers in _07_layout.scss without anything changing. Do you have any suggestions about what to change?

**Comment by Phlow** [comment]
Have a look into _/_sass/_07_layout.scss_

You can adjust the logo according to the breakpoints.

For example for medium-view

```
@media #{$medium-only} {
    #logo img {
        margin-top: 60px;
    }
```

A Suggestion: Never place a logo on a big screen in the center. That doesn't look good. No big websites doing something like this.

**Comment by Harold-Anderson** [comment]
Thank you for the design tip.  

It seems to me that Grav is a simpler and more robust system.  I got the idea to check out Grav from your Twitter feed.  Thank you for that.

If you want help with the English on your web site,  I would be happy to help.

**Comment by Phlow** [comment]
I understand your thoughts: Jekyll is quite complex. The advantage over Grav: It's static. No security issues, clean HTML and you can truly optimize the hell out of your sites. But to learn everything takes a while.

**Comment by Harold-Anderson** [comment]
I am obviously not an expert, or a developer like you are.  However, this reminds me of the early days of Linux, circa Redhat 5.2 in 1999.

Right now, there is a major problem with Wordpress:  It is overly complex and therefore unstable, insecure, and slow.  So the idea of a static CMS solves all these problems.  However,  both Grav and Jekyll require  user proficiency att css and html coding.  Even something as simple as flowing text around a picture is an all-day task for a newbie.  Microsoft Word has easily done this for over 20 years.

There is a lot of room for a static CMS that can do most design tasks without css knowledge.  Until that happens, Jekyll and Grav will remain niche products for professionals.

**Comment by Phlow** [comment]
You are right. Jekyll is nothing for _normal_ useres. It's for webdesigners, developers. But Grav is really easy to set up. Easier than WordPress :) And WordPress is quite complex as you mentioned. With its Admin Panel, I think Grav is quite good and easy for newbies.

**Comment by TWiStErRob** [comment]
Did either of you try squarespace? I didn't, I just always hear they sponsor YouTube vids.

**Comment by Harold-Anderson** [comment]
No, I am too busy trying to figure out how to flow text around my profile picture in Grav to try Squarespace.   Endless changing of css files without any result, no documentation, and a forum full of experts who don't answer questions.
