### ISSUE TITLE
Footer About/Credits/Services always in capital letters

### ISSUE THREAD

**Issue by liftmybeard** [Phlow/feeling-responsive#111]
Hello,

I've managed to find out that the titles in the footer are found in `_data`, but is there a way to change the fact that whatever I type remains in CAPS?

I've also looked into `_footer.html` but I'm pretty sure the setting for this behavior is not there. What am I missing?

Thanks in advance,

Michele.

**Comment by TWiStErRob** [comment]
https://github.com/Phlow/feeling-responsive/blob/c26677b70450d537dea3cfcad9afcafa283bc8b2/_sass/_07_layout.scss#L284

**Comment by liftmybeard** [comment]
@TWiStErRob Thank you!

**Comment by Phlow** [comment]
CSS :) Thanks for helping @TWiStErRob
