### ISSUE TITLE
Jekyll brings built-in Theme support, will you?

### ISSUE THREAD

**Issue by TWiStErRob** [Phlow/feeling-responsive#112]
I don't know if you follow the news, you might be interested in this: https://jekyllrb.com/docs/themes/
It might be a good idea to transition to that distribution mechanism.

**Comment by Phlow** [comment]
Yes I know about it. I followed some threads. Currently I don't have the time to port the theme and make it a gem. For beginners the whole install theme thing is still confusing, in my opinion. Maybe I do it in december. Currently I have to much to do.

Have you seen [this thread about it](https://talk.jekyllrb.com/t/gem-packed-themes-taking-the-docs-for-real/2932)?

**Comment by TWiStErRob** [comment]
Hmm, interesting discussion.
