### ISSUE TITLE
Change Rouge highlighting colors

### ISSUE THREAD

**Issue by HelloAnneKim** [Phlow/feeling-responsive#115]
How do I change the rouge highlighting colors?  The default seems to be a light green background with a couple different pinks and blues.  I attempted to rougify the _11_syntax-highlighting.scss but it didn't change anything.

**Comment by TWiStErRob** [comment]
`.highlight` is declared with white background there, but if you look at the structure on the site:
![image](https://cloud.githubusercontent.com/assets/2906988/19020227/28567ef8-88a3-11e6-844d-a6c38adcdbf4.png)
you can see that the green color is attached on the `<code>` element, which is coming from [_06_typography.scss](https://github.com/Phlow/feeling-responsive/blob/cb70c94d6e9cc3bf47db9856f9ca1253b0a28ce4/_sass/_06_typography.scss#L178) &rarr; [_01_settings_colors.scss](https://github.com/Phlow/feeling-responsive/blob/cb70c94d6e9cc3bf47db9856f9ca1253b0a28ce4/_sass/_01_settings_colors.scss#L124).

**Comment by HelloAnneKim** [comment]
ah.  That was very very helpful!  So I change the code highlighting by changing the elements in [_01_settings_colors.scss](https://github.com/Phlow/feeling-responsive/blob/cb70c94d6e9cc3bf47db9856f9ca1253b0a28ce4/_sass/_01_settings_colors.scss#L124)

Is there any automatic way I can make these elements the [monokai](https://github.com/richleland/pygments-css/blob/master/monokai.css) theme?  I already rougified [_11_syntax_highlighting_monokai.scss](https://github.com/herroannekim/herroannekim.github.io/blob/master/_sass/_11_syntax-highlighting_monokai.scss)
Or maybe I should switch to pygment?

**Comment by TWiStErRob** [comment]
I don't think there's an automatic way, I suggest you change 01 and 11 files, maybe the files in `assets/css` if you want to do something clever like changing your code theme from _config.yml.

@phlow is there anything I'm missing?

**Comment by Phlow** [comment]
No there is no automatic way. Sorry.
