### ISSUE TITLE
Hardcoded path to /blog for blog entries

### ISSUE THREAD

**Issue by lbeltrame** [Phlow/feeling-responsive#12]
I would like to have the frontpage to actually show blog posts. While I can fix that easily with the metadata, some other links like the archive require the ``/blog`` directory to be present. Is this by purpose, or an oversight?

**Comment by Phlow** [comment]
This is by purpose. And currently the frontpage is showing blog-posts. Have a look into the [frontpage-layout](https://github.com/Phlow/feeling-responsive/blob/gh-pages/_layouts/frontpage.html). You can customize the template for example to only show blog-posts.

*Feeling Responsive* wants to be more than just a theme for blogging. But if you need a blog, you can use it with the help of the blog-folder. Look into the configuration file to change paths and so on.

I hope this helps you.

**Comment by lbeltrame** [comment]
I'm not against it: it's just that it would break migrations from other blogging platforms (creating loads of broken links), but if this theme's structure is so by design, it will have to do.
