### ISSUE TITLE
Heading anchors not output in HTML

### ISSUE THREAD

**Issue by ghost** [Phlow/feeling-responsive#120]
First off, great work on producing such a well put together theme. It's obvious you put a lot of time and attention to detail into this. Thank you so much for your efforts, skill and generosity.

I'm opening this issue to start documenting a list of things which could be done to improve the accessibility of this theme.

Please add items one at a time and give a 👍 or 👎  if you'd like to see them added.

**Comment by ghost** [comment]
**Heading anchors.** All headings H1..H6 should output an `id` attribute with a slugified version of the heading text. This affords the ability to deep link to content using the fragment identifier.

**Comment by TWiStErRob** [comment]
@jhabdas that exists, see for example https://phlow.github.io/feeling-responsive/design/typography/typography/#about-volkhov-lth2gt

**Comment by ghost** [comment]
@TWiStErRob I downloaded this theme yesterday from https://github.com/Phlow/feeling-responsive/archive/gh-pages.zip and heading anchors are not enabled in the default config provided.

**Comment by TWiStErRob** [comment]
That's really weird, considering I linked the live version of that code, served by GitHub. [`auto-ids`](http://kramdown.gettalong.org/options.html#option-auto-ids) is true by default. Did you by any chance change to `markdown: rdiscount` to be compatible with your old blog posts?

**Comment by ghost** [comment]
The config file contained in the above zip is set to use `markdown: kramdown`. I haven't modified the markdown processor. I'm serving locally right now using Jekyll 3.3.1.

**Comment by TWiStErRob** [comment]
Hmm, that's getting stranger. I just downloaded the file you linked, extracted without changes, `bundle update`, `bundle exec jekyll serve`, visited http://localhost:4000/feeling-responsive/design/typography/typography/ and the headings have IDs. All headings coming from markdown get IDs, but the `<h1>` coming from `page.html` doesn't, but that's expected.

Jekyll 3.3.1 as well, kramdown 1.13.1; Windows 10 x64, ruby 2.3.1p112 (2016-04-26 revision 54768) [x64-mingw32]

**Comment by ghost** [comment]
That info was useful. I'd've never expected any header *not* to have an `auto_id` unless disabled. When I access said page I also see the anchors for the content headers. But what I want is to create my own layouts in HTML and have all Headings auto-tagged, automatically.

I'll close this for now as IDs are present in Markdown headers (only, it seems), which could've been a design choice. Please let me know if this is not the desired behavior with a reopen. Thanks for the help!

**Comment by TWiStErRob** [comment]
I don't know if that's possible. Given that the current slugs are added by kramdown, all the others need to be processed as well. I think you would need a post-processor, something operating like [Compress](http://jch.penibelst.de/). This is, of course, only needed if you want to go fully automated.

A partial solution is to write your own heading: `{% include heading level=3 text='Blah blah' %}`
Create a file as `_includes/heading` with contents:
```
<h{{include.level}} id={{include.text | slugify}}>{{include.text}}</h{{include.level}}>
```
The above is untested, given only to convey the idea.

**Comment by Phlow** [comment]
You Can define it via kramdown

<http://kramdown.gettalong.org/syntax.html#specifying-a-header-id>

**Comment by TWiStErRob** [comment]
@Phlow that won't affect [this](https://github.com/Phlow/feeling-responsive/blob/912b3cd7583aa93ff4b8c52d1c3c243f7b1de6c6/_layouts/page.html#L27) one.

**Comment by Phlow** [comment]
Ah, ok, than I would suggest:

    <h1 id="{{ page.title | slugify }}">{{ page.title }}</h1>

Would that solve the problem?

**Comment by ghost** [comment]
@Phlow something like that would indeed, but FR layouts have a back-to-top anchor already. In my case I'm building layout based on Collection filtering and will be using a name assigned to a collection element. No problem, just wish the generator (i.e. Jekyll) had a setting for applying ids to all headers and a Liquid assignment should help me do it. :)

**Comment by ghost** [comment]
Quick aside on accessibility. How do you guys feel about PhotoSwipe on mobile, arrow key functionality for nav elements and a skip-nav widget, anchoring down to content?

**Comment by Phlow** [comment]
The current version of *Feeling Responsive* uses the image gallery by Foundation 5.

Currently I am working on *Feeling Responsive V2* where I already integrated Foundation 6. Foundation 6 has no gallery, so <http://photoswipe.com/> could be a great alternative.

**Comment by jhabdas** [comment]
superb!

**Comment by ghost** [comment]
I'm going to list additional accessibility items in a running list below as I encounter them in order to save on open issues for consideration during the port to F6:

- [ ] `alt` attribute on Gallery images (use `{{ item.caption }}`) for improved screen reader support
- [ ] Drop-down menu accepts arrow key gestures
- [ ] Page titles and content use [`smartify` filter](https://github.com/jekyll/jekyll/pull/4333/) to output emphasized dash when `--` is used
- [x] Bug: Heading anchors covered by global navigation (fixed, see [this comment](https://github.com/Phlow/feeling-responsive/issues/120#issuecomment-264236727))
- [ ] TOC smooth scrolls to heading anchors ([example with anchor.js](https://habd.as/awesome-react-boilerplates/))
- [ ] Return to top link smooth-scrolls with inertia scrolling to top anchor
- [ ] As discussed, [PhotoSwipe](http://photoswipe.com/)
- [ ] Lazy-loaded images with [LQIP](http://www.guypo.com/introducing-lqip-low-quality-image-placeholders/)
- [ ] Skipnav at first tab index
- [ ] Google-free search. Keep users on the site longer with a search tool like that integrated with Michael Rose's open source [So Simple](https://github.com/mmistakes/so-simple-theme) theme.

I'll keep listing as I go as I'm spiking very rapidly on a site right now. Additional feedback on customizability will be offered as I get there. Thanks for producing such good documentation.

**Additional ideas**

- [ ] [Static commenting system](https://mademistakes.com/articles/jekyll-static-comments/)
- [ ] Include `Gemfile` with functional version of developer dependencies. Consider building a [GH-compatible pipeline](https://github.com/jhabdas/habd.as/blob/master/Gemfile) still [ready for PageSpeed 100](https://habd.as/pagespeed-100-with-jekyll-s3-and-cloudfront/) as.
- [ ] Build pipeline could augo-generate image thumbs (here's [one for Hugo using Gulp](https://github.com/adrinux/web-starter-hugo), and an [example `Rakefile`](https://github.com/jhabdas/habd.as/blob/master/Rakefile.rb) for sticking with Ruby where possible) [dev experience]
- [ ] Ideally some responsive image includes using [`srcset` attr](http://devdocs.io/html/attributes#srcset-attribute) for device-aware downloads [ux]
- [ ] Pipeline may include ability to auto-blur small images (e.g. [CSS Blur Effect](https://mademistakes.com/til/css-blur-effect/)) [ux]
- [ ] Back to Table of Contents snippet added to `_includes` or programmatically generated based on a flag in the frontmatter [dev/editor experience]
- [ ] Ability to add [filters](http://devdocs.io/css/filter) to hero images via frontmatter or on a site-wide basis via config (i.e. grayscale or opacity) ([example opacity filter on `habd.as`](https://github.com/jhabdas/habd.as/blame/master/_posts/2016-09-19-choose-hugo-over-jekyll.md#L17)) [dev/design/publisher experience]
- [ ] Allow default switching to masthead with text in a more systematic way [dev experience]

**Comment by TWiStErRob** [comment]
I solved heading anchors covered at http://www.twisterrob.net/blog/tags/#collection with https://github.com/TWiStErRob/twisterrob.github.io/blob/0ba9f2696ba3ec1105166927f0e1bdd4e3dfb2bd/_sass/_09_elements.scss#L179-L189

**Comment by jhabdas** [comment]
@TWiStErRob I'm digging your header customizations! Got a commit number for the header color manipulation by chance? Thanks for being open source.
