### ISSUE TITLE
Google search doesn't work on mobile

### ISSUE THREAD

**Issue by clhenrick** [Phlow/feeling-responsive#125]
The search box default says "enter search term and hit enter" but there is not a clear way to "hit enter" on iOS. 

![image](https://cloud.githubusercontent.com/assets/161748/21152611/e224ccee-c11b-11e6-9672-2abc9d0f3052.png)

I fixed this problem by adding a submit button below the input within the form like so:

```html
<form id="search" onsubmit="google_search(); return false;">
	<input type="text" id="google-search" placeholder="{{ site.data.language.enter_search_term }}">
	<button class="radius" type="submit">Submit</button>
</form>
```

And by changing the `site.data.language.enter_search_term` to be "Enter search term and hit submit", not sure what the German translation would be.

I can submit a PR if you'd like.

**Comment by ghost** [comment]
You'd want to press "Go" on the soft keyboard in such a situation. IMO Google should not be used as the search provider because it a) only allows indexed pages to be searched and b) takes people away from the website, resulting in a bounce. Instead, I'd suggest incorporating a system like what Michael Rose did with his [So Simple theme](https://github.com/mmistakes/so-simple-theme), possibly with some enhancements to UX leveraging something like [Typeahead with Bloodhound](https://habd.as/talks/typeahead-with-bloodhound/).

**Comment by clhenrick** [comment]
I'm not sure what you mean by "press Go on the soft keyboard", here's what the keyboard looks like on iOS when you click on the input field:

![image](https://cloud.githubusercontent.com/assets/161748/21155371/c05581fc-c126-11e6-81fe-c8c4ac016232.png)

I'm sure there are better options for implementing a search in a site, I'm offering a simple solution to the current code base.

**Comment by ghost** [comment]
Set type=search on input for proper HTML5 form semantics

**Comment by clhenrick** [comment]
Adding `type=search` to the text input doesn't bring up the "Go" button on
iOS keyboard for me.


-Chris
clhenrick.io

**Comment by ghost** [comment]
Bummer. Sounds like a Safari issue. Does "Return" submit the search now? Browsers are responsible for doing something with the attributes. Here's more detail: http://devdocs.io/html/element/input

Good luck!

**Comment by Phlow** [comment]
I have already changed the search function for the next release. It will be lunr.js – It's not good for big sites, but most of the forks I found don't have so many pages, so I guess lunr.js with an option to use google or duckduckgo will be a good choice. You can check out lunr.js already in my other theme <https://phlow.github.io/simplicity/search/>
