### ISSUE TITLE
Custom URL

### ISSUE THREAD

**Issue by rakeshkotla123** [Phlow/feeling-responsive#128]
I am Pretty much new to this technology. I used custom domain with you repository however I couldn't see my domain name when I enter other navigation elements and I can pretty much only see your domain "https://phlow.github.io/feeling-responsive/headers/" on all other links. 
This is my custom website name "fundukes.com".  How can I change all other links to this domain?

**Comment by ghost** [comment]
http://jekyllrb.com/docs/configuration/
