### ISSUE TITLE
SCSS conversion error

### ISSUE THREAD

**Issue by prokoudine** [Phlow/feeling-responsive#13]
While pushing to remote branch, without any SCSS customization:

remote:       Generating... 
remote:   Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/styles_feeling_responsive.scss':
remote:                     Invalid CSS after "...ules: $modules ": expected "}", was "!global;" on line 13
remote: jekyll 2.5.3 | Error:  Invalid CSS after "...ules: $modules ": expected "}", was "!global;" on line 13

Local instance of Jekyll just works though. Any hints much appreciated.

**Comment by prokoudine** [comment]
This is Jekyll 2.5.3 on the server btw.

**Comment by Phlow** [comment]
I am not so deep into the code of Jekyll and no expert. I suggest you ask the question in [talk.jekyllrb.com](http://talk.jekyllrb.com). There are the experts for such problems. My theme works locally and on github pages fine and I use it all the time myself. Sorry.

**Comment by prokoudine** [comment]
Just FYI, as it turned out, the problem was with sass 3.2 installed which didn't support !global. Installing 3.4.13 (any >= 3.3 would do) fixed this.

**Comment by Phlow** [comment]
Thank you for letting me know :)
