### ISSUE TITLE
Dropdown to dropdown in navigation

### ISSUE THREAD

**Issue by bsde1245** [Phlow/feeling-responsive#130]
Hi, thanks for the nice theme. I have a question, is it possible to add dropdown further to dropdown of the navigation item. Hope you understood. Thanks.

**Comment by TWiStErRob** [comment]
With the current structure it's not possible, see https://github.com/Phlow/feeling-responsive/blob/gh-pages/_includes/_navigation.html

However I've written a recursive implementation, see https://github.com/TWiStErRob/twisterrob.github.io/blob/master/_includes/navigation.html and `navigation_link.html`.

**Comment by fedemengo** [comment]
Is this still working?

**Comment by Phlow** [comment]
@fedemengo Is what working?
