### ISSUE TITLE
problem of building website

### ISSUE THREAD

**Issue by liangdesign** [Phlow/feeling-responsive#132]
I used your theme to build a jekyll site locally and uploaded files to Github. I got a message like below:

 Your site is having problems building: Your SCSS file assets/css/styles_feeling_responsive.scss has an error on line 10: File to import not found or unreadable: foundation-components/top-bar. Load paths: _sass /hoosegow/.bundle/ruby/2.3.0/gems/jekyll-theme-primer-0.1.7/_sass. For more information, see https://help.github.com/articles/page-build-failed-invalid-sass-or-scss/.

I tried uploading files in _site, and got similar message like below:

Your site is having problems building: Your SCSS file assets/css/atom.scss has an error on line 3: File to import not found or unreadable: functions.scss. Load path: /hoosegow/.bundle/ruby/2.3.0/gems/jekyll-theme-primer-0.1.7/_sass. For more information, see https://help.github.com/articles/page-build-failed-invalid-sass-or-scss/.

How can I resolve this? Thanks.

**Comment by ghost** [comment]
@liangdesign I highly encourage you to take this concern to StackOverflow, where others can be rewarded for their help. Opening help tickets on GitHub is ill-advised for Open Source repos supported by individuals.

**Comment by liangdesign** [comment]
@jhabdas Thanks your advice. I'am new to this.

**Comment by ghost** [comment]
We all gotta start somewhere. You picked a great place to start. :)
