### ISSUE TITLE
Your theme is listed in jekyll-themes.com

### ISSUE THREAD

**Issue by Redgadget** [Phlow/feeling-responsive#133]
Your theme has been listed on [https://jekyll-themes.com/](https://jekyll-themes.com/).

**Comment by ghost** [comment]
@Redgadget how is the sort order determined?

**Comment by Redgadget** [comment]
They are sorted in no particular order. Now on, new themes show up first.

**Comment by ghost** [comment]
@Redgadget May I suggest splitting the site into two sections:

- Recently updated (using sorted date of last commit)
- Most popular (leveraging the [`jekyll-ga` plugin](https://github.com/developmentseed/jekyll-ga))

Doing so will help your users understand which themes are most popular (not just the ones that have the highest star rating) and which are the newest. You can mitigate this need by increasing the pagination limit to reduce number of pages and adding lazyloaded images to conserve bandwidth.

**Comment by ghost** [comment]
Note also I've been informed http://jekyll.tips is undergoing an overhaul, which I assume includes its templates section.

**Comment by Redgadget** [comment]
@jhabdas Thanks for the suggestion. I'm already sorting new submissions based on date.
I was also thinking about sorting based on number of stars. And about `jekyll-ga` - to be honest analytics super-proxy is a little tedious to implement.

**Comment by ghost** [comment]
@Redgadget stars will do it. IMHO it's not a true barometer of popularity as it relies primarily on social influence (easier for those with more power already) as opposed to letting the little guys shine based on UGC, making your site more unique.

**Comment by Redgadget** [comment]
I have seen jekyll.tips template section. They have a good collection. Lazy loading images will definitely help. I will try that. 
And true. Same is true for number of forks. 
I guess people look for say  photography theme,  minimal layout, resume etc., If they get what they want, popularity doesn't matter.

**Comment by ghost** [comment]
@Redgadget very groovy. one thing Hugo got right with their theme system was requiring theme authors to provide metadata along with their theme submissions. be nice to see jekyll themes drive towards a similar pattern. as for lazyloading, I left an example implementation here using lazysizes: https://github.com/comfusion/after-dark#intelligent-lazyloading

**Comment by Redgadget** [comment]
Wow that looks cool :+1:   Do you have the same theme for Jekyll as well?

And there are already other websites listing Jekyll themes. But, they aren't giving any credit to theme developers. I thought they deserve a mention somewhere.

**Comment by ghost** [comment]
@Redgadget I haven't gotten around to porting After Dark to Jekyll, but my Hugo implementation may help guide doing it, while helping highlight some of the affordances of Go templates in Hugo over liquid and Jekyll. If I have my way we'll add lazyloading in [feeling-responsive-v2](https://github.com/Phlow/feeling-responsive-v2).

As for other theme sites, your guess is as good as mine. 😸

**Comment by ghost** [comment]
Ah, but things to be aware of:

- https://learn.siteleaf.com/themes/gem-based-themes/
- http://www.jekyll-plugins.com/plugins?utf8=%E2%9C%93&query=theme

And it may be valuable to parse the new GH tags feature to help snag additional themes, if you're not using it already.

**Comment by Redgadget** [comment]
Thanks. I see that gem based themes are gonna take over these themes. Maybe I should list gem based themes as well.
Thanks for the guide. 
And GH tags are called topics I guess. That's how I'm getting new themes (searching for jekyll-themes with fewer number of forks filter).

**Comment by ghost** [comment]
And, sorry for the verbosity here, looking through these may help surface themes as well:

- https://html5up.net (looking for Jekyll ports)
- https://github.com/spf13/hugoThemes (looking for Jekyll ports)
- And it'd be good to include [some of Michael Rose's Jekyll themes](https://mademistakes.com/work/jekyll-themes/) for excellence in design

**Comment by Redgadget** [comment]
Thanks. That's a huge list. Let me see what I can do.
I have already included most of his themes!

**Comment by Phlow** [comment]
Thankyou for listing *Feeling Responsive* @Redgadget
