### ISSUE TITLE
Add Last Modified Datetime to Meta

### ISSUE THREAD

**Issue by ghost** [Phlow/feeling-responsive#136]
Feeling Responsive includes `_meta_information.html` when `show_meta` is truthy. Meta information output includes the `date` with a calendar icon. It would be beneficial for user agents and the Web infrastructure if we also included the last modified time.

Last modified time can be included using the `jekyll-last-modified-at` gem. Here's an example update to the meta info include file to incorporate this data when the gem is present (and enabled via config):

```liquid
{% if page.date %}
  <span class="icon-calendar pr20"> Published: <time datetime="{{ page.date | date_to_xmlschema }}" itemprop="datePublished"> {{ page.date | date: "%Y-%m-%d" }}</time></span>
{% endif %}
{% if page.last_modified_at %}
  <span class="icon-calendar pr20"> Updated: <time datetime="{{ page.last_modified_at | date_to_xmlschema }}" itemprop="datePublished"> {{ page.last_modified_at | date: "%Y-%m-%d" }}</time></span>
{% endif %}
````

The above looks like this when output:

<img width="600" alt="screen shot 2017-02-28 at 3 15 19 pm" src="https://cloud.githubusercontent.com/assets/440298/23395292/c9ea6de8-fdc8-11e6-9a47-ff6dd1e524d3.png">

**Considerations:**

This is a little verbose, mind you, as user agents and readers alike may benefit from conditionally visually displaying one or the other depending on which is available and more recent. In other words, only show one calendar icon and date, specify which it is (one of Published or Last Modified), but output both, if available, to the page (one as `meta` with microformat data, or using JSON-LD).

**Comment by TWiStErRob** [comment]
Is this plugin whitelisted in gh-pages?

**Comment by ghost** [comment]
You can check here: https://github.com/github/pages-gem/blob/master/lib/github-pages/plugins.rb

**Comment by TWiStErRob** [comment]
So, that's a no... I don't think it's worth dropping pages support for this.

**Comment by ghost** [comment]
https://github.com/jekyll/jekyll-seo-tag/pull/151/files#r103643150

**Comment by ghost** [comment]
@pathawks weighed, suggestion GH pages may never be able to support the Last-Modified-At gem. Maybe we'll see some kind of support built into Jekyll in the future, otherwise it can be achieved via front matter for those who are interested. That said, I'm using it currently with CloudCannon on the ChicagoGangHistory website and it works gloriously.

Ref: https://github.com/github/pages-gem/pull/119

**Comment by ghost** [comment]
I jumped the gun on closing this. I believe the gem may still see GH pages support once some validation occurs.
