### ISSUE TITLE
Use variables in landing page widget settings

### ISSUE THREAD

**Issue by cownby** [Phlow/feeling-responsive#139]
Love this theme! Would be really nice to use "{{ site.url }}{{site.baseurl}}/ for the widget definitions in feeling-responsive/pages/pages-root-folder/index.md instead of hardcoding the links.  Is this a problem because the widget definitions are front-matter?

**Comment by TWiStErRob** [comment]
If you look at https://github.com/Phlow/feeling-responsive/blob/gh-pages/_includes/_frontpage-widget.html#L2 you'll see that any relative URLs will be used exactly as you want it.

**Comment by cownby** [comment]
Fancy that, it does work!  Thank you for your patient response.
