### ISSUE TITLE
Fontawesome images not shown

### ISSUE THREAD

**Issue by drseb** [Phlow/feeling-responsive#14]
Hi,

after playing around with your theme for several hours, I have to say it looks really great and seems to be exactly what I was searching for. But now I can't seem to be able to build the images (e.g. github-icon), that I guess are take from font-awesome. Please see attached screenshot. I can't build them within my own branch or when using a fresh clone of your repository. 

Thanks for any help,
Sebastian

![screen shot 2015-05-12 at 14 47 57](https://cloud.githubusercontent.com/assets/5172897/7587440/7a285464-f8b6-11e4-9841-a9c356b28794.png)

**Comment by Phlow** [comment]
Hi Seb! The icons I use for *Feeling Responsive* are from http://entypo.com/

You find them in *assets/fonts/svg-files-for-custom-font/* – With some knowledge and http://fontcustom.com/ you can build your own font.

Everything should work out of the box. Can you point me to your theme? I guess something was not uploaded properly.

**Comment by drseb** [comment]
Here is what I did
```Shell
git clone https://github.com/Phlow/feeling-responsive.git
cd feeling-responsive/
jekyll serve --config _config.yml,_config_dev.yml
```
Then entered the URL http://127.0.0.1:4000/ into Chrome.

I did this 5 minutes ago, now on a different machine, but again the icons are not shown properly.
I am on MacOS 10.10.3.

Do you see any mistake?

Thanks for any help,
Sebastian

**Comment by Phlow** [comment]
Ah, cool. I got this. Chrome doesn't load sometimes content from other domains.

Try to enter *http://localhost:4000/*

Or change the URL in *_config_dev.yml* to http://127.0.0.1:4000/ 

    url: "http://127.0.0.1:4000"
    urlimg: "http://127.0.0.1:4000/images/"

Tell me, if it worked.

I remember wasting hours to figure this out.

**Comment by drseb** [comment]
Same problem with Firefox by the way. Thanks for your hint. Using "localhost" instead of "127.0.0.1" did the job for me. 
I can imagine that it took a while to find this out!!
