### ISSUE TITLE
Unable to use embedded trinket.io script with theme

### ISSUE THREAD

**Issue by ponicboy** [Phlow/feeling-responsive#140]
Using jekyll-tools (https://github.com/trinketapp/jekyll-tools) to include an interactive python trinket.io frame on a page but the theme formats the code inside the snippet all in ONE line instead of multiple lines and with indentation.
See example here: https://pythonice.github.io/feeling-responsive/design/no-header/

My guess is there could be a conflict in stylesheets or other formatting. The script code can be found in _includes/trinket-open. Interestingly when I build locally I don't see this issue, only when deploying to GitHub pages.

Any help would be appreciated!

Example of another theme where it works: https://ponicboy.github.io/minimal-mistakes/first-post/

Otherwise really enjoying this theme, thank you!

**Comment by Phlow** [comment]
open `_layouts/default.html` and comment or delete `layout: compress` :) The compress-layout minifies the HTML-code into one line.

    ---
    # layout: compress
    ---

**Comment by ponicboy** [comment]
That fixed it! 😄

Thanks so much for the quick response!

**Comment by ghost** [comment]
@ponicboy that plug-in looks pretty old and never gained traction. You may want to consider an alternative approach using something like https://runkit.com/ or similar depending on your needs. Good luck!

**Comment by ponicboy** [comment]
@jhabdas Wow Runkit looks awesome! Thanks for pointing this out, I'm going to give it a try. My goal is to create python snippets the user can interact with for leaning purposes.

**Comment by ghost** [comment]
@ponicboy cool. if RunKit doesn't support a python runtime somehow perhaps CodePen will meet your needs. have fun out there
