### ISSUE TITLE
compiles always with localhost

### ISSUE THREAD

**Issue by nkundiushuti** [Phlow/feeling-responsive#141]
I have an issue with the config file. even I put the values correctly in the config file to point out to my domain, I even the deleted the config_dev just to make sure and it is still compiling with localhost:4000 unless i force it with --host and --port.

I am running OSX 10.8  and I worked with feeling-responsive not with the barebones.

**Comment by TWiStErRob** [comment]
Are you trying to compile on gh-pages, or locally? Did you clean your `_site` folder?

**Comment by nkundiushuti** [comment]
I am compiling locally, I deleted the _site folder. It doesn't happen with the images, only with the other files (there is another setting for the images there). 
I tried also with the flag --config. Could it be something general overwriting this? 
I have everything here:
https://github.com/nkundiushuti/webpage

**Comment by TWiStErRob** [comment]
<strike>Why are you building the site yourself? GH-pages could do it for you, all you need to do is to move the jekyll source files from master to gh-pages, and then you can access at https://nkundiushuti.github.io/webpage/; or you could just switch the branch: https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#enabling-github-pages-to-publish-your-site-from-master-or-gh-pages x</strike> ... ah, I see `scholar`, never mind.

re `localhost`: I tried cloning your repo and building `master` and the same happens for me, there's no mention of `localhost` in the config, but it builds with that. I'm not sure what goes wrong, sorry. Maybe @Phlow or @jhabdas will have some insight.

**Comment by nkundiushuti** [comment]
maybe it's jekyll scholar? though I don't see how's this related.
the same happens with the barebones version.

**Comment by ghost** [comment]
@nkundiushuti I believe using localhost is a feature to help prevent individuals from having to toggle the `url` back-and-forth during development. This is similar to how Hugo works. Try setting `JEKYLL_ENV=production` when starting your build.

`JEKYLL_ENV=production jekyll serve`

If that works you can `brew install ngrok` then do `ngrok http 4000`, copy the URL into your config, restart with the command above and test over the wire.

**Comment by ghost** [comment]
FYI: http://jekyllrb.com/docs/configuration/

**Comment by ghost** [comment]
@nkundiushuti also, I noticed https://github.com/nkundiushuti/webpage/blob/master/_config_dev.yml#L9. if you're serving from root you _do not_ want to set `baseurl` to the empty string (it needs to be `Nil`). you can set it to nil by doing one of these guys:

```yaml
baseurl: #'/feeling-responsive'
```

**Comment by ghost** [comment]
@nkundiushuti can this be closed now?

**Comment by nkundiushuti** [comment]
sure! thank you for your help! 
JEKYLL_ENV=production jekyll serve 
worked!
