### ISSUE TITLE
Use GA Async Tag

### ISSUE THREAD

**Issue by ghost** [Phlow/feeling-responsive#142]
Move to `head` (more info on why below) to allow analytics script preloading in modern browsers. My tests show a ~5 point bump in PageSpeed by switching from `script` at the bottom of the body. I haven't tested against the current theme use of the [DOM Script Tag](https://www.stevesouders.com/blog/2009/04/27/loading-scripts-without-blocking/) method, but I'm confident tests will reveal an improvement if moved.

https://developers.google.com/analytics/devguides/collection/analyticsjs/

> While the [the old snippet] ensures the script will be loaded and executed asynchronously on all browsers, it has the disadvantage of not allowing modern browsers to preload the script.

```html
<script>
window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
ga('create', '{{ site.analytics.google.tracking_id }}', 'auto');
ga('send', 'pageview');
</script>
<script async src='https://www.google-analytics.com/analytics.js'></script>
```

I'd recommend placing any `async` scripts above any external blocking requests in the head (i.e. before the external stylesheets) for maximum benefit. Doing so will kick off the async download before the parser gets blocked waiting the external stylesheet requests.

**Comment by inetbiz** [comment]
@Phlow this should help!

**Comment by Phlow** [comment]
Finally added
