### ISSUE TITLE
Gallery pictures get cut of by caption

### ISSUE THREAD

**Issue by ghost** [Phlow/feeling-responsive#144]
Portrait oriented images do not completely display in the lightbox when a caption is used.

**Comment by Phlow** [comment]
That should be a Foundation 5 problem. I can't solve it. More information about foundation 5 on this webpage <http://foundation.zurb.com/sites/docs/v/5.5.3/components/clearing.html>

**Comment by ghost** [comment]
How about changing the CSS into a transparant background?
