### ISSUE TITLE
Jekyll error

### ISSUE THREAD

**Issue by mvasin** [Phlow/feeling-responsive#15]
When I run "jekyll serve", I get error:

Liquid Exception: Included file '_includes/list-posts.html' not found in feeling-responsive/_posts/design/2014-07-09-post-left-sidebar.md

Included file '_includes/list-posts.html' not found

**Comment by Phlow** [comment]
Hey Mike!

I downloaded the repo and tried it myself and everything worked. The file Jekyll is searching for is in the folder [*_includes/*](https://github.com/Phlow/feeling-responsive/tree/gh-pages/_includes)

Have a look into that folder, if *list-posts.html* is missing, you can download it again from the repo.

If it still doesn't work, try to download the whole repository again. And run it.

I hope it works.

Greets and thanks trying out *Feeling Responsive*.

Moritz

**Comment by mvasin** [comment]
Yes, I messed up a little bit - I ran "jekyll serve" and didn't notice all the files are in the inner 'responsive' folder. Now it's OK. I dropped you an email about transferring my site www.skorosvadba.ru to Jekyll. Did you see it?

**Comment by Phlow** [comment]
Glad you asked for the email. It landed in my spam folder... I will answer it.
