### ISSUE TITLE
Cannot Export HTML Pages using RSS

### ISSUE THREAD

**Issue by ghost** [Phlow/feeling-responsive#151]
I'm trying to migrate my site off Jekyll but cannot get a clean RSS 2.0 feed including pages.

**To Reproduce**

1. Generate the `feed.xml` after swapping `site.posts` for `site.html_pages`.
  
    **WARNING:** Take care not to output your `letsencrypt.txt` or other secrets to the feed! 😄 
1. Remove or conditionally apply `pubDate` element from `feed.xml` as pages may not be dated.

**Actual result**

Search the generated feed file for `{%` and discover unprocessed templates. Output not fully processed and shows the following, for example:

    {% for post in site.tags.header %}

**Expected result**

Output fully processed.

**Comment by jhabdas** [comment]
To reproduce just swap `site.posts` in `feed.xml` with `site.html_pages`.

**Comment by ghost** [comment]
I take it back. It's a Jekyll issue. To confirm I simply created a `feed.custom.xml` in my site root and saw the same issue after moving all the goods from `/pages/` into the root as well. Weird.

**Comment by TWiStErRob** [comment]
Did you open a Jekyll issue?

**Comment by jhabdas** [comment]
I was 80% of the way there but couldn't create a reduced test case. Turns out it only happens some of the time. More work needed before I can identify root cause and I'm not going to put it on them.

**Comment by jhabdas** [comment]
Ahem, by some of the time, I mean all of the time with some of my pages. Idempotent.

**Comment by jhabdas** [comment]
I gave up trying to fix this on this in my modified clone running an earlier version of Feeling Responsive. I tried a number of patterns and approaches to solving the problem short of rebuilding the site from scratch. I'm pulling down a fresh clone of master in attempt to reproduce this. If I do I'll reopen. Otherwise it's time to improvise.

**Comment by ghost** [comment]
Okay. Reproduced on `master`. Reopening. Updated initial comment with clearer steps to reproduce. This bug blocks users from outputting RSS feeds containing data necessary to lift their sites out of Jekyll.

I'm going to give Atom a shot. But I was hoping to use RSS 2.0 to get my exports as RSS 2.0 is used by Hugo and, therefore, the lowest-common denominator for static websites I care about.

**Comment by ghost** [comment]
@Phlow feel free to close this as a `wontfix`. Just wanted to raise awareness. I'm already grateful for how far Feeling Responsive has gotten me. And I took many things away form studying its source. Probably my favorite feature is the XSLT for feeds (I added that feature to `jekyll-feed` about a year ago but for the life of me couldn't find a good template to use - yours is bomb).

**Comment by Phlow** [comment]
OK.

**Comment by ghost** [comment]
Got past this with a customized `jekyll-feed` to do the heavy lifting. Outputs `site.html_pages` like a champ. Huzzah.
