### ISSUE TITLE
How to determine raw file’s extension within template

### ISSUE THREAD

**Issue by zlinuxboy** [Phlow/feeling-responsive#152]
recently, I would like add toc within a html which was generated by asciidoctor. but most of the jekyll theme do not compatibale with asciidoctor. So I have to custom a template by my self:

within template, such as layout:post

```
{% if file.ext == "adoc" %}
	blah blah
{% elsif file.ext == "markdown" %}
	blah blah
{% endif %}
```

the file.ext variable doesn't exist actually.so, here is the problem: how to determine the markup file's extension?

**Comment by Phlow** [comment]
This is a complicated non-theme-related question. You should ask it here › https://talk.jekyllrb.com/new
