### ISSUE TITLE
table of contents link seems to jump to the wrong location

### ISSUE THREAD

**Issue by bkiefer** [Phlow/feeling-responsive#155]
When I press one of the items in the table of contents in the documentation page, the corresponding tile and part of the text are covered by the navigation bar. What's the way to change that?

**Comment by ghost** [comment]
@bkiefer had the same question. it's answered in old issues. keep digging! 👍

**Comment by TWiStErRob** [comment]
https://github.com/Phlow/feeling-responsive/issues/120#issuecomment-264236727
