### ISSUE TITLE
Can you add pagination-v2 ?

### ISSUE THREAD

**Issue by ArchGalileu** [Phlow/feeling-responsive#158]
Hello @Phlow 

Many thanks for your work, it is amazing ;)

I don't know much about jekyll, but learning, could you update to pagination-v2 ?

Best regards
ArchGalileu

**Comment by Phlow** [comment]
Hello @ArchGalileu – You have to do it yourself. This gem is not supported by GitHub Pages › https://pages.github.com/versions/

I want *Feeling Responsive* to work with GitHub Pages :)
