### ISSUE TITLE
google site search isn't working - specifically the site: prefix is having no effect.

### ISSUE THREAD

**Issue by ph-hs** [Phlow/feeling-responsive#16]
I tried to get https://developers.google.com/custom-search/ working too, yet the CSS for feeling-responsive is clashing with Google's CSS for the search box and search button.

**Comment by Phlow** [comment]
Do you have any suggestion what I could do better. Google Custom Search is always a little bit nasty and difficult to style. That's why I used the simple Google Search approach.

**Comment by ph-hs** [comment]
I agree with your synopsis, and complaint against the new Google stuff.  The trouble is that the old way is broken too. I see you're constructing a URL in JavaScript but haven't seen why it's going wrong on the post-redirect-get ?  Say I search for portfolio in yours, here's what I get when I arrive at Google.com:

![image](https://cloud.githubusercontent.com/assets/10211993/7942582/fee89340-092c-11e5-9958-ec8ca2f9975a.png)

**Comment by Phlow** [comment]
I really have no clue. If I use it like this <https://www.google.de/search?q=portfolio+site:https://phlow.github.io/feeling-responsive> – it works...

It's important, that you fill out the variable called `site:` in `_config.yml` – that builds the search. It nothing special and you're the first you has problems with it.
