### ISSUE TITLE
Add yelp social icon

### ISSUE THREAD

**Issue by aaaallinacall** [Phlow/feeling-responsive#166]
For general commercial applications

**Comment by Phlow** [comment]
If you need it, you can do it yourself. Just add it to the font :)

**Comment by vruetten** [comment]
Hi,
Thanks for the great template.
I've been trying to add the trip advisor logo for some time.
Could you give a step by step description of all the necessary steps required to add the logo.
(e.g.: "add it to the font" - fontcustom.yml? does one need to edit other files, and so forth)

Sorry to have to ask,
Thanks a lot,

Best,

Ginny

**Comment by TWiStErRob** [comment]
@vrutten read https://github.com/Phlow/feeling-responsive/issues/76
