### ISSUE TITLE
Missing baseurl in the barebone version ?

### ISSUE THREAD

**Issue by arnaud-m** [Phlow/feeling-responsive#172]
Hi, 

Thank you for your theme. I am wondering why the commit ' 	I hate baseurl – Clean up of missing baseurls on all pages'  (37f9b544fd64720edacc3a0ba99e8d1f01727b0c) has not been merge in the barebone branch ? 
I have some issues with the baseurl in the _includes/_navigations.yml. 

Thanks by advance.
Arnaud

p.s. by the way, I also hate baseurl ;)

**Comment by Phlow** [comment]
hey @arnaud-m , I am very sorry. The barebones version isn't up-to-date – I should delete it. Meanwhile most of the time those filters are the best :) I used them already in the non-barebones version.

~~~~
{{ "/assets/style.css" | absolute_url }}
{{ "/assets/style.css" | relative_url }}
~~~~

More about it at https://jekyllrb.com/docs/liquid/filters/

**Comment by arnaud-m** [comment]
Thank you @phlow. 
So, Should I try to merge my fork with the master branch to update the theme ?

**Comment by Phlow** [comment]
I guess so… Please be careful! I can't asure you that it will work perfectly :(
