### ISSUE TITLE
Choose to show logo or not for each page

### ISSUE THREAD

**Issue by mgalland** [Phlow/feeling-responsive#173]
Hi, 
I wonder if there is a way to choose to display the logo or not for each page independently. 
For instance, to show the logo on the homepage but to hide it on the other pages for instance.
I checked issue #163 but it seems to be for the whole website as far as I can see. 
Thanks!
Marc

**Comment by Phlow** [comment]
Hello @mgalland – hack the theme :)

have a look into `_config.yml` and the Default Settings.

The line

~~~~
      show_meta: false 	# Hide metadata for all pages
~~~~~

defines a switch.

~~~~
{% if page.show_meta == true %}
{% include _meta_information.html %}
{% endif %}
~~~~


and in your pages/posts:

~~~~
---
layout: page
title: ""
show_meta: false
---

your post
~~~~


Make a switch for the logo yourself.

Than edit the code where the logo is set and use an if-statement.

Via frontmatter in your pages and posts you can now turn on and off the logo.
