### ISSUE TITLE
Common page width

### ISSUE THREAD

**Issue by peter-sc** [Phlow/feeling-responsive#174]
Hi, is it please possible to define a common width for the whole page, including menu, header, footer, subfooter? Currently the width is 1000px, but the menu is stretched on the whole page, also the background color for footer and subfooter is not limited to 1000px. 
Is there a way to include a background picture for the footer instead of color?

Many thanks
Peter

**Comment by Phlow** [comment]
Hey @peter-sc – Have a look at `_04_settings_global.scss` and the code here:

~~~
// b. Grid
// - - - - - - - - - - - - - - - - - - - - - - - - -

// $include-html-grid-classes: $include-html-classes;
// $include-xl-html-grid-classes: false;

// $row-width: rem-calc(1000);
// $total-columns: 12;
// $column-gutter: rem-calc(30);
~~~

That should help you :)

**Comment by peter-sc** [comment]
@Phlow I see can control the row-width via $row-width, which changes the footer width as well.
Is it possible to limit the width of the background color, which is filled to the left and right from footer/subfooter? Currently the footer background color is full-width. I'd like to limit it to $row-width too.
Thanks :)

**Comment by Phlow** [comment]
That are very specific questions. I am sorry, but you have to figure them out yourself. The whole theme is based on the foundation framework. More on https://foundation.zurb.com/sites/docs/v/5.5.3/ :)
