### ISSUE TITLE
Front page site name is not updated

### ISSUE THREAD

**Issue by fedorov** [Phlow/feeling-responsive#180]
I updated site name and slogan in `_config.yml`, as instructed in the [getting started guide](https://phlow.github.io/feeling-responsive/getting-started/), see specific changes [here](https://github.com/OSIPI/osipi.github.io/commit/ea73b5384ae0cf5a3b98d4a1c85136790479567a#diff-aeb42283af8ef8e9da40ededd3ae2ab2R11). However, the front page is still showing "Feeling Responsive" overlay text, and the text I populated shows in the tooltip instead, see deployed site here: https://osipi.github.io/. I spent quite some time, but can't figure out where this text is coming from!

**Comment by TWiStErRob** [comment]
That's an image, inspect the element.

**Comment by fedorov** [comment]
Indeed, so trivial. Sorry for the noise.

**Comment by fedorov** [comment]
And thank you!

**Comment by Phlow** [comment]
You‘re welcome. And Robert: As always thanks for the lightspeed answer.
