### ISSUE TITLE
Theme not found using Github supported remote_theme in _config.yml

### ISSUE THREAD

**Issue by Darilbii** [Phlow/feeling-responsive#182]
I developed a initial build of my site locally which renders fine, however when I tried to push it onto github the theme doesn't load.

Tried having this in the _config.yml:
`remote_theme: Phlow/feeling-responsive`

Got the following error:
`Incremental build: disabled. Enable with --incremental`
      `Generating... `
      `Remote Theme: Using theme phlow/feeling-responsive`
`jekyll 3.7.4 | Error:  404 - Not Found`

I want to prevent just copying all of the files and placing them in my own site so that I can give you credit for your work.

**Comment by Darilbii** [comment]
Found the solution. This is due to the theme branch being `gh-pages` 

so I should have had the following in my _config.yml
`remote_theme: Phlow/feeling-responsive@gh-pages`

I think it would be a good idea to  include this information in the **Getting Started** Page of the theme's demo site. This would help others when trying to use your theme in the future

**Comment by Phlow** [comment]
Hey @Darilbii I donˋt quite understand the error. But you ´re welcome to add your suggestion to the Getting Started Page. Just make a pull request. And thankyou for giving me credit for using the theme. Itˋs much appreciated 👍🏻
