### ISSUE TITLE
Modify urlimg in _config.yml

### ISSUE THREAD

**Issue by inetbiz** [Phlow/feeling-responsive#186]
Been looking at how one might make that link more dynamic instead of static @Phlow and check out the answer at https://stackoverflow.com/questions/55665544/how-can-i-create-a-jekyll-variable-from-another-in-config-yml/55679645#55679645

**Comment by Phlow** [comment]
The best way is to get rid off this old idea. When [Jekyll introduced](https://jekyllrb.com/docs/liquid/filters/)

    {{ "/images/cat.jpg" | absolute_url }}

all changed. In other projects I already deleted urlimg because it's no more necessary and makes it _unflexible_ and a little more _complicated_.
