### ISSUE TITLE
Rotating background images

### ISSUE THREAD

**Issue by fedorov** [Phlow/feeling-responsive#187]
Is it possible somehow to configure the front page to rotate images from a list, or pick a random image from a list, on each page load? From a quick look, I found this one - https://getbootstrap.com/docs/4.0/components/carousel/ - is this something that can be integrated with the front page template?

**Comment by Phlow** [comment]
No, it is not implemented. But you it is possible with the Foundation Framework. But you have to try it yourself. I am by far no javascript expert :(
