### ISSUE TITLE
implement jekyll-feed

### ISSUE THREAD

**Issue by inetbiz** [Phlow/feeling-responsive#188]
Frontmatter would have to change. The tags for **image** to **images** then add
```
---
image:
    path: {{ page.images.thumb }}
---
```
Wherever possible and change the code in layouts so it doesn't conflict with

**Comment by Phlow** [comment]
Hey Denver, I will look into your proposals as soon as possible. Currently I have a lot to do and this theme is just a fun project. So, it has not my top priority.
