### ISSUE TITLE
Tags functionallity?

### ISSUE THREAD

**Issue by ikusalic** [Phlow/feeling-responsive#190]
This is really a great theme!

I'm wondering about the tags support. Looking though repo and examples, I see that there is some support for tags. But it seems only to be there for visual purposes? They don't seem to be clickable, and there isn't any tags summary page, so the tag functionality seems a bit confusing and limited. Am I missing something? Are there any plans for extending the tags functionallity?

**Comment by TWiStErRob** [comment]
Hey @ikusalic, I have a website based on this theme. I've implemented tags.

Tags page: http://www.twisterrob.net/blog/tags/
source: [tags.html](https://github.com/TWiStErRob/twisterrob.github.io/blob/master/blog/tags.html)

Tags cloud on sidebar: http://www.twisterrob.net/blog/
source: [sidebar.html](https://github.com/TWiStErRob/twisterrob.github.io/blob/master/_includes/sidebar.html#L2-L6) + [tag_cloud.html](https://github.com/TWiStErRob/twisterrob.github.io/blob/master/_includes/tag_cloud.html)

Clickable tags on top of the post: http://www.twisterrob.net/blog/2016/02/blog-formatting.html
source [meta_information.html](https://github.com/TWiStErRob/twisterrob.github.io/blob/master/_includes/meta_information.html#L19-L27)

Menu for tags at Blog > Tags > ...
source [navigation.yml](https://github.com/TWiStErRob/twisterrob.github.io/blob/master/_data/navigation.yml) + [navigation_link_special.html](https://github.com/TWiStErRob/twisterrob.github.io/blob/master/_includes/navigation_link_special.html)

**Comment by ikusalic** [comment]
Ah, perfect! Thank you.
