### ISSUE TITLE
Multiple accordion-posts on the same page

### ISSUE THREAD

**Issue by mpelleau** [Phlow/feeling-responsive#191]
When several accordion-posts are on the same page, if you click on for instance the third item of the first accordion, it opens all the third items of all the accordions. They must have the same id I guess.
Any idea how to fix it?

An example here: http://i3s.unice.fr/master-info/programme/semestre1/

**Comment by mpelleau** [comment]
I've deleted the line `{% assign counter = 1 %}`, in the file _includes/accordion-posts and it fixes the problem.

**Comment by Phlow** [comment]
Hey @mpelleau thank you for figuring it out. If I delete the code line with the counter, does it also work if you only use one accordion?

**Comment by mpelleau** [comment]
It seems to, for instance on this page: http://i3s.unice.fr/master-info/blog/archive/
It's just that the first panel will not have a number as `counter` is not set to anything.

**Comment by Phlow** [comment]
Thank you for helping me out. I will correct the problem.

**Comment by Phlow** [comment]
It's me again… I can't find __includes/accordion-posts_ – I searched all files and there is only one appearance of `{% assign counter = 1 %}` – it's in _/blog/archive.html_

Or am I blind?

**Comment by mpelleau** [comment]
I have an old version of your theme... Apparently now you have list-posts with no counter, so I guess this issue is resolved :)
