### ISSUE TITLE
include a gemspec in the gh-pages branch

### ISSUE THREAD

**Issue by thedavidmeister** [Phlow/feeling-responsive#194]
discussion here https://github.com/Phlow/feeling-responsive/issues/193

**Comment by cgodefroy** [comment]
Yes, it would be helpful, especially for Amplify which needs the git repo address and branch.

**Comment by thedavidmeister** [comment]
@Phlow as the bare bones version was deleted without adding/copying the gemspec across i've got failing builds now that can't be fixed until this happens :(

**Comment by ifreund** [comment]
The unannounced deletion of the bare bones branch broke my site as well.

**Comment by Phlow** [comment]
I am truly sorry. I didn‘t know, that when I delete something in my repo It would affect other repositories.

**Comment by ifreund** [comment]
I mean in retrospect I should have forked your repo and based my build off of that, but I didn't so the build failure was pretty confusing till I realized the branch here was gone.

**Comment by Phlow** [comment]
Please have a look at the normal version. There you should find all the necessary parts.

**Comment by thedavidmeister** [comment]
@Phlow i still don't see a gemspec https://bundler.io/man/gemfile.5.html#GEMSPEC file in the normal version

this is what is needed (and was removed):

https://github.com/thedavidmeister/feeling-responsive/blob/2020-01-09-art/jekyll-theme-feeling-responsive.gemspec

**Comment by Phlow** [comment]
Can you make a pull request and I add it.

**Comment by thedavidmeister** [comment]
@Phlow i'm a bit confused because the original gemspec came from you... it's just that it was in one branch and not the other...

**Comment by Phlow** [comment]
It was a suggestion › I found the original source › https://github.com/Phlow/feeling-responsive/pull/159

Please make a pull request and I add it. I don't really know what the gemspec does ;)

**Comment by thedavidmeister** [comment]
@Phlow the gemspec allows someone to point to the github repo and have ruby pull the theme in, rather than copying and pasting and committing a bunch of files

that way every file in the repo is just an override, which makes it more maintainable

https://jekyllrb.com/docs/themes/#understanding-gem-based-themes

**Comment by Phlow** [comment]
OK. I understand. Do you make a pull request for the desired file? That's the easiest for me.

**Comment by Phlow** [comment]
Added.
