### ISSUE TITLE
Absolute URL in navigation.yml is prefixed by site.url, but it should not

### ISSUE THREAD

**Issue by fedorov** [Phlow/feeling-responsive#195]
I configured one of the top-level navigation items to point to an external https URL, but somehow it is prefixed by the base URL.

The way I understand, it is configured in this line:
https://github.com/fedorov/idc-feeling-responsive/blob/gh-pages/_data/navigation.yml#L18,
and it parameterizes this template (or whatever it is called), and this line tells it should not prefix with domain, but for whatever reason it does prefix it:
https://github.com/fedorov/idc-feeling-responsive/blob/gh-pages/_includes/_navigation.html#L30.

Any thoughts what I am doing wrong?

**Comment by fedorov** [comment]
I could not figure this out quickly, so I just removed those menu items, so links above will not work for the master. The tree of the code with the issue is here: https://github.com/fedorov/idc-feeling-responsive/tree/acdf94d3ad858bb172c65c3ff2d26ea0968f0445.

https://github.com/fedorov/idc-feeling-responsive/blob/acdf94d3ad858bb172c65c3ff2d26ea0968f0445/_data/navigation.yml#L18

**Comment by fedorov** [comment]
@notZaki figured it out in this PR: https://github.com/fedorov/idc-feeling-responsive/pull/1

**Comment by fedorov** [comment]
@Phlow isn't this something that should be fixed in this repository: https://github.com/ImagingDataCommons/imagingdatacommons.github.io/pull/1/files#diff-279d32205f7efe0a57bb5c60fe477b70R32

**Comment by Phlow** [comment]
I fixed it. Forgot to push it ;)

**Comment by fedorov** [comment]
got it! for completeness, this was fixed in https://github.com/Phlow/feeling-responsive/commit/6f027f1546d8ce88d4efef5d7fdec9a8c76734d2#diff-279d32205f7efe0a57bb5c60fe477b70
