### ISSUE TITLE
How to change theme to suit right handed languages

### ISSUE THREAD

**Issue by MuhammadIbnAlAbbas** [Phlow/feeling-responsive#197]
how to change theme to suit right handed languages so that it changes from being left aligned:

![Screenshot_2019-12-24 يل يبلاسب لايبل تيلاتن بل ا الحياة](https://user-images.githubusercontent.com/53350464/71383857-2f98e600-25d6-11ea-9f1c-73b89b2d60e8.png)

to become right aligned:
![Screenshot_2019-12-24 سر بسم الله الرحمن الرحيم - موضوع](https://user-images.githubusercontent.com/53350464/71383885-5525ef80-25d6-11ea-8536-70fa34bd477b.png)

**Comment by MuhammadIbnAlAbbas** [comment]
I have found solution for content in default layout.
`  <div style="text-align: right"> {{ content }} </div> `

will do 
but how to change next and blog archive so that next become on left and blog archive on right
in blog layout?
![Screenshot_2019-12-24 Blog of Feeling Responsive](https://user-images.githubusercontent.com/53350464/71384626-535e2b00-25da-11ea-852a-a33faf7abfcd.png)

**Comment by TWiStErRob** [comment]
Does this help? https://stackoverflow.com/a/2546347/253468

**Comment by MuhammadIbnAlAbbas** [comment]
Yes thank you
`<body style="direction: rtl">`  works in default layout much better than right aligned :)

**Comment by MuhammadIbnAlAbbas** [comment]
I have reversed the order of 3 footer raw columns in _includes/_footer.html 
I think everything is good for right language support except for drop triangular button in navigation 
how to make the triangular shaped symbol on navigation on left not right ?
is it in css or scss or in _includes/_footer.html ?

**Comment by TWiStErRob** [comment]
If you right click the triangle and click Inspect, you can see that it's inside the `<a` tag as `:after`. The `<a` has a `.has-dropdown`. This is a class from Foundation as you can see if you search the code: https://github.com/Phlow/feeling-responsive/search?q=has-dropdown. The alignment is done by `right: 0` from
https://github.com/Phlow/feeling-responsive/blob/fc22dc626225e2eede981ae284c3a876f8a340c3/_sass/foundation-components/_top-bar.scss#L387

It looks like you need to configure Foundation to be rtl and set the opposite direction too:
https://github.com/Phlow/feeling-responsive/blob/fc22dc626225e2eede981ae284c3a876f8a340c3/_sass/_04_settings_global.scss#L146-L147
see also https://get.foundation/sites/docs/rtl.html

**Comment by MuhammadIbnAlAbbas** [comment]
Ok works more better.
So to summarize to change that theme to right handed languages, you only have to add those lines in _sass/_04_settings_global.scss : 
` $text-direction: rtl;`
` $opposite-direction: left;`

and to add `<body style="direction: rtl">` 
or `style="direction: rtl"` 
to compress and redirect layouts in _layouts and in navigation head footer in _includes.
Thank you :)

**Comment by MuhammadIbnAlAbbas** [comment]
I love that theme.
It's good and I have adjusted it and I thank @TWiStErRob for his customization of it.
Everything is good for web view but in mobile view there is one issue:

when you choose 
$text-direction: rtl;
$opposite-direction: left;
in scss files
The  navbar menu doesn't show drop downs when you click on any button that have drop down.
In the image below if you click on Templates or documentation it won't view the drop down list.
Is these problem in JavaScript ?
Any ideas?



![Screenshot_2020-01-10 Feeling Responsive](https://user-images.githubusercontent.com/53350464/72219803-ab8daa80-3552-11ea-9a4a-c689e50e81f6.jpg)

**Comment by Phlow** [comment]
Hey @MuhammadIbnAlAbbas 

I can't help you because I am no Javascript expert. This theme uses the Foundation Framework – They have a https://foundation.discourse.group/ – Maybe you can find an answer there.
