### ISSUE TITLE
Link color in Buttons is same as Button background color

### ISSUE THREAD

**Issue by kanishkkunal** [Phlow/feeling-responsive#2]
Link text color in Buttons is same as Button background color resulting in unreadable buttons unless one hovers over it or has the link visited already. Here's the screenclip: 
![Issue Image](http://i.imgur.com/1RcLEqP.png)

Following may go into _09_elements.scss 
a.button {
  color: #ffffff;
}

**Comment by Phlow** [comment]
Thank you. I stumbled upon this bug, too. I think it's fixed now. Greets from Germany, mo.

**Comment by Phlow** [comment]
fixed #2
