### ISSUE TITLE
jekyll-redirect-from doesn't work

### ISSUE THREAD

**Issue by bolaurent** [Phlow/feeling-responsive#202]
I tried installing jekyll-redirect-from on my site derived from feeling-responsive. It doesn't work; it tries to redirect to an url whose value is the empty string ("").

I downloaded the unmodified template, added jekyll-redirect-from, and ran it locally. Same result.

**Comment by Phlow** [comment]
Hello @bolaurent – You dont need a plugin. There is a layout for that, which does the same:

https://github.com/Phlow/feeling-responsive/blob/gh-pages/_layouts/redirect.html

Best practice is to use a .htaccess-file instead. For example:

~~~
redirect 301 /file.html http://domain.de/new-file.html
~~~
