### ISSUE TITLE
Blog page as landing page

### ISSUE THREAD

**Issue by YohanObadia** [Phlow/feeling-responsive#203]
How can you remove the index.html page and use the blog.html page instead when only typing the base url ?

Basically I want people to arrive immediately on my blog page.

Amazing template btw, thanks you very much for it !

**Comment by Phlow** [comment]
I guess you just have to change the permalinks ;)

**Comment by Phlow** [comment]
Make the blog layout your index.html page and it should work.

**Comment by YohanObadia** [comment]
Thanks, in the end I understood better what the home page was displaying (i.e. the first blog post) and it is super elegant so I keep it :)
