### ISSUE TITLE
Am i the the only one stucked at publishing this theme on github page?

### ISSUE THREAD

**Issue by fdq09eca** [Phlow/feeling-responsive#210]
It has been stuck at the ready to be published status for half an hour. all I did is just forking this repo, do I need to make any adjustment to get it rolling?

![image](https://user-images.githubusercontent.com/51902242/86456670-00b5b680-bd55-11ea-8476-9aab0bfe5923.png)

**Comment by Phlow** [comment]
I think so, you're the first to ask in years ;)

Probably you should check out the [GitHub Pages Guide](https://guides.github.com/features/pages/)

It took me some time, too, to understand the whole thang.

**Comment by fdq09eca** [comment]
it works after i chose a random default theme, Thank you. But.. why?
I was using minimal mistake which requires an `index.html` at the root, why it is different in this theme? Sorry, I am new.
