### ISSUE TITLE
Internal anchors scroll page such that heading renders behind top nav

### ISSUE THREAD

**Issue by markcmiller86** [Phlow/feeling-responsive#216]
I often create pages with internal links...for example a set of bullets that then ref. major headings later on the same page. I do so using *normal* markdown support for auto-anchors. For an example, go to [this page](https://visit-dav.github.io/visit-website/support/) and then click on either of the two links in the first bullet list. It winds up going to the correct anchor but the page scroll doesn't take into account the top nav bar and so it winds up scrolling the anchored ref such that it is hidden by the top nav bar.

Is there any way to adjust this using the css stuff?

**Comment by Phlow** [comment]
There's one simple option.

in _https://github.com/Phlow/feeling-responsive/blob/gh-pages/_includes/_navigation.html_

Just delete `class="sticky"` – Than it won't be sticky anymore. Or you give every heading an extra padding/margin at the top.

~~~
<div id="navigation" class="sticky">
~~~

**Comment by markcmiller86** [comment]
Thanks @Phlow! :clap: That does fix the issue...but at the expense of loosing the nav when scrolled

Regarding the padding/margin approach...would that involve touching more of the  sass/css content to finding all the instances where h1...h6 are styled and adjusting them somehow?

**Comment by Phlow** [comment]
@markcmiller86 You can change everything as it pleases you. I have no time to spare. My theme is just an offering ;)

**Comment by markcmiller86** [comment]
BTW...I happened to find this html hack that seems to work ok...https://css-tricks.com/hash-tag-links-padding/

**Comment by Phlow** [comment]
@markcmiller86 That might really fix the problem. Unfortunately I have no time to "repair" it. You're invited to help out :)
