### ISSUE TITLE
Not compatible with a CNAME?

### ISSUE THREAD

**Issue by felixinx** [Phlow/feeling-responsive#22]
Hi,

When I load [my website](http://felixinx.me), all the CSS and JS dosen't dispaly.
Here is the console error log;

`(index):1 GET https://felixinx.me/assets/css/styles_feeling_responsive.css net::ERR_CONNECTION_TIMED_OUT`

`(index):1 GET https://felixinx.me/assets/js/modernizr.min.js net::ERR_CONNECTION_TIMED_OUT`

`(index):1 GET https://felixinx.me/assets/js/javascript.min.js net::ERR_CONNECTION_TIMED_OUT`

`(index):1 GET https://felixinx.me/assets/img/logo.png net::ERR_CONNECTION_TIMED_OUT`

`(index):1 Uncaught ReferenceError: $ is not defined(anonymous function) @ (index):1`

`(index):1 GET http://www.google-analytics.com/analytics.js net::ERR_BLOCKED_BY_CLIENT(anonymous function) @ (index):1(anonymous function) @ (index):1`

`/assets/img/touch-icon-192x192.png:1 GET https://felixinx.me/assets/img/touch-icon-192x192.png net::ERR_CONNECTION_TIMED_OUT`

`/assets/img/touch-icon-192x192.png:1 GET https://felixinx.me/assets/img/touch-icon-192x192.png net::ERR_CONNECTION_TIMED_OUT`

`/assets/img/touch-icon-192x192.png:1 GET https://felixinx.me/assets/img/touch-icon-192x192.png net::ERR_CONNECTION_TIMED_OUT`

`/assets/img/favicon-32x32.png:1 GET https://felixinx.me/assets/img/favicon-32x32.png n`

As you can see, my website cannot reach all the files. You can access my [configuration here](https://github.com/felixinx/felixinx.github.io/blob/master/_config.yml)

Thanks

**Comment by Phlow** [comment]
Please set

    baseurl: "http://felixinx.me"

to

    baseurl: ""

More on <https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/>

:)

**Comment by felixinx** [comment]
Thanks!

**Comment by Phlow** [comment]
You're welcome :)
