### ISSUE TITLE
No navigation in iPhone portrait mode?

### ISSUE THREAD

**Issue by amunn** [Phlow/feeling-responsive#223]
Visiting the [feeling-responsive](https://phlow.github.io/feeling-responsive/) site on iPhone running iOS 14.3 there is no navigation menu in portrait mode, just the search link. The NAV menu does appear on the iPhone in landscape mode. The NAV menu appears correctly in portrait mode on an iPad running iOS 14.2.

Is this a known problem?

![2021-01-14 21 23 35](https://user-images.githubusercontent.com/633053/104674120-1109ff00-56b1-11eb-9924-9c1bccb24b98.png)

**Comment by Phlow** [comment]
Hey @amunn – You're right. That's new. Currently I have no clue, why. Didn't change a thing. It has to do something with the breakpoints I guess. I put it onto my todo-list. Can't tell you, when I have the time to correct the misbehaviour.

**Comment by Phlow** [comment]
It has to do something with a new commit. My old version on my computer behaves perfect. I will see into it.

**Comment by zenofx** [comment]
Don't know 100% if this is related, but the "hamburger" menu icon vanished on our site on current Safari versions (iPhone and also OSX desktop). After a little bit of fiddling, I realized Safari doesn't display box shadows for elements with height 0 any more (the hamburger is implemented as box shadow). I'm pretty sure this used to work as I always test our site with my iPhone :)

My **ugly** workaround: Change "height" for hamburger in foundation-components/_global.scss:133 to "0.1px".

**Comment by IamSreeman** [comment]
@Phlow this issue is there in Android and on any device which has portrait mode also. Try to resolve this as soon as you can.

**Comment by Phlow** [comment]
You're welcome to help out :)

**Comment by amunn** [comment]
I don't know if this is helpful, but if you open the page with any web browser (tested on MacOS, not iOS) you can replicate the behaviour if you resize the window beyond a certain point. Here are three images from Firefox. The first shows the menu bar at a width where everything is displayed.

![Screen Shot 2021-06-07 at 6 51 43 PM](https://user-images.githubusercontent.com/633053/121097310-c99c2080-c7c1-11eb-9c86-fdd98e41d97e.png)

The next shows the menu bar when you reduce the window width so that all items don't fit. This correctly shows just the navigation menu.

![Screen Shot 2021-06-07 at 6 51 57 PM](https://user-images.githubusercontent.com/633053/121097406-ee909380-c7c1-11eb-9b1e-d7b4d04ceeec.png)

But if you reduce the window size yet further, the navigation menu disappears and you are left with the Search menu (which is the first element displayed in the navigation menu dropdown).

![Screen Shot 2021-06-07 at 6 52 15 PM](https://user-images.githubusercontent.com/633053/121097571-30b9d500-c7c2-11eb-95e3-b14e4a49ec91.png)

So the problem is much more generally related to how the top navigation bar is displayed dependent on width.

**Comment by psprint** [comment]
I'm having the same issue at http://neomcedit.software. Please fix, as the theme is exceptionally good and I want still to use it.

**Comment by TWiStErRob** [comment]
It does not repro on Chrome when using an iPhone device, the collapsed/expanded menu works as expected.

| Collapsed | Expanded |
|-|-|
| ![image](https://user-images.githubusercontent.com/2906988/122107603-2a0b0d80-ce13-11eb-9545-30ac46ddb91a.png) | ![image](https://user-images.githubusercontent.com/2906988/122107517-0f389900-ce13-11eb-82ad-57db468d455e.png) |

And it works fine on Pixel 2 XL, latest-ish Chrome too. @IamSreeman what are your details?

**Comment by psprint** [comment]
Yes, because I've found a work around:

``` 
 12│ diff --git a/_includes/_navigation.html b/_includes/_navigation.html
 13│ index 884fdc9..5316d90 100644
 14│ --- a/_includes/_navigation.html
 15│ +++ b/_includes/_navigation.html
 16│ @@ -8,7 +8,6 @@
 17│    <nav class="top-bar" role="navigation" data-topbar>
 18│      <ul class="title-area">
 19│        <li class="name">
 20│ -      <h1 class="show-for-small-only"><a href="{{ site.url }}{{ site.baseurl }}" class="i
 21│      </li>
 22│         <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just
 23│        <li class="toggle-topbar menu-icon"><a href="#"><span>Nav</span></a></li>
```

However, I'm still having the issue with menu not pulling down on desktop Chrome…

**Comment by IamSreeman** [comment]
@TWiStErRob you are not getting that error because @psprint solved it. Feeling responsive still has that error as shown in the below picture
![Capture](https://user-images.githubusercontent.com/62174391/122161517-7b58e280-ce8f-11eb-858d-72026432d7d6.PNG)
It's there on android also, but if I on desktop site mode it will be resolved.
![1](https://user-images.githubusercontent.com/62174391/122161876-279ac900-ce90-11eb-9b48-16fa2382e7d7.jpeg)
![2](https://user-images.githubusercontent.com/62174391/122161880-29648c80-ce90-11eb-8ad9-8c8b965faed4.jpeg)
![3](https://user-images.githubusercontent.com/62174391/122161883-29fd2300-ce90-11eb-9880-f70229e87678.jpeg)

On desktop it will occur when we resize the window as below.
https://user-images.githubusercontent.com/62174391/122161990-63ce2980-ce90-11eb-996b-1a751d2fae3a.mp4

**Comment by Phlow** [comment]
Dear people!

[This commit](https://github.com/Phlow/feeling-responsive/commit/60bac8f2faac163e916567988f989773da93cd5a) destroyed unfortunately the mobile nav. I deleted the changes and it works again. Please check and leave a reply.

Stay healthy, mo.
