### ISSUE TITLE
Missing qualifier in css

### ISSUE THREAD

**Issue by TWiStErRob** [Phlow/feeling-responsive#23]
You might want to add `#` for these `footer`s to prevent styling section and article footers.
https://github.com/Phlow/feeling-responsive/blob/gh-pages/_sass/_07_layout.scss#L261

In general: is there any reason why you don't use this SCSS stlye?
```css
#footer {
    ...
    p,
    li {
        ...
    }
}
```
I noticed there's some indendtation pattern instead.

**Comment by Phlow** [comment]
You are right. I change it like so, to address also the subfooter.

~~~~
#footer-content p,
#footer-content li {
    font-size: rem-calc(13);
    font-weight: 300;
}
~~~~
