### ISSUE TITLE
Question Regarding caption_url Functionality

### ISSUE THREAD

**Issue by Linux-Geezer** [Phlow/feeling-responsive#230]
I've been playing around with the Feeling Responsive theme in an attempt to try and learn how it works so I can modify it for my needs for my blog.

I'm trying to figure out how the "caption_url" in some of the Markdown files works. I would like to modify the functionality of the "caption_url" to open in a new tab/window instead of the same window.

Is the following function under the "javascript.js" file under the "assets/js" folder the mechanism that generates the caption link?

<! -- code -->
caption : function (container, $image) {
var caption = $image.attr('data-caption');

if (caption) {
container
.html(caption)
.show();
} else {
container
.text('')
.hide();
}
return this;
},
<! -- /code -->

**Comment by TWiStErRob** [comment]
https://github.com/Phlow/feeling-responsive/search?q=caption_url&type=

**Comment by TWiStErRob** [comment]
A blog post in _posts defines a layout in the _layouts folder mostly "page" which inherits from "default" which includes _masthead.html which has the condition to insert the header based on the page yaml metadata.

**Comment by Phlow** [comment]
Just edit this file › feeling-responsive/_includes/_masthead.html

and add `target="_blank"` :)

    <a href="{{ page.header.caption_url }}" target="_blank">{{ page.header.caption }}</a>
