### ISSUE TITLE
Full Width Image Headers

### ISSUE THREAD

**Issue by Linux-Geezer** [Phlow/feeling-responsive#232]
Is there an ideal image resolution to use for full width, or fullwidth, image headers that will show the complete image; i.e. not cut off part of the image? I've played around with a few different resolutions and nothing seems to work. When using an image for a site header, I want it to display as the image does in an image viewer; i.e. nothing gets cut off.

**Comment by Phlow** [comment]
There is no perfect resolution for the _full-width_ header.

Howeever you get an option for images in the header to resize properly according to their size. Have a look at:

* <https://phlow.github.io/feeling-responsive/design/header-image-pattern/>
* <https://phlow.github.io/feeling-responsive/design/header-image-color/>

Hope, that helps.

**Comment by Linux-Geezer** [comment]
Using a background pattern or color to properly resize an image is not a good option in my opinion. But thank you for your reply.

**Comment by Phlow** [comment]
It's a matter of taste. I wanted the header not to be oversize on small screens and still be responsive. But the beauty of this theme is: you can change it to the way you like it :)

You have to look into backstretch › https://github.com/Phlow/feeling-responsive/search?q=backstretch

<em>Feeling Responsive</em> uses <a href='http://srobbin.com/jquery-plugins/backstretch/'>Backstretch by Scott Robin</a> to expand them from left to right. The width should be 1600 pixel or higher using a ratio like 16:9 or 21:9 or 2:1."
