### ISSUE TITLE
Broken link "style your header" in https://phlow.github.io/feeling-responsive/documentation/#title-images 

### ISSUE THREAD

**Issue by chipmuenk** [Phlow/feeling-responsive#233]
The mentioned link points to https://phlow.github.io/headers/

Beautiful theme b.t.w. !

**Comment by Phlow** [comment]
Thank you. I corrected the broken link :)

**Comment by Phlow** [comment]
Danke für den Tipp!

**Comment by chipmuenk** [comment]
Purer Eigennutz - das ist meine erste Jekyll-generierte Homepage und ich nehme jede Hilfe, die ich bekommen kann  :-)
