### ISSUE TITLE
Various missing icons?

### ISSUE THREAD

**Issue by chipmuenk** [Phlow/feeling-responsive#234]
Not sure how important or correct this is but the favicon checker https://realfavicongenerator.net/ reported quite a lot of missing icons and other stuff when running a first check with a github page based on feeling-responsive. I also ran the checker on phlow.github.io with similar results. 

Perhaps the results are just marketing scam but maybe it is interesting for you anyway.

**Comment by Phlow** [comment]
I checked it.

https://realfavicongenerator.net/favicon_checker?protocol=https&site=phlow.github.io%2Ffeeling-responsive%2F

There are some missing. You're welcome to add the missing favicons.

But there are already plenty of favicons, you find all of them in this file:

https://github.com/Phlow/feeling-responsive/blob/gh-pages/_includes/_favicon.html

To me that seems enough :)

**Comment by chipmuenk** [comment]
> There are some missing. You're welcome to add the missing favicons.

No, thanks - I agree that there are more than enough :-)
