### ISSUE TITLE
Please add a Light/Dark toggle button

### ISSUE THREAD

**Issue by SageofPHY6Paths** [Phlow/feeling-responsive#237]
An example is shown here: [https://varun.ca/dark-mode/](https://varun.ca/dark-mode/)

<img src="https://user-images.githubusercontent.com/92218586/139112644-00e052b1-1e27-4f21-b1fb-99759f26955e.png"  width="300"/>
<img src="https://user-images.githubusercontent.com/92218586/139112576-75df96c5-dab8-46d0-b9bd-26d62d11ed3c.png"  width="300"/>

I searched and found in many places how to implement it, but they all were related to CSS. I couldn't found how to do it using SCSS.

Can this option be added to feeling responsive? It should look like this: (**the toggle icon can be just right to the CONTACT in the nav bar** )
![image](https://user-images.githubusercontent.com/92218586/139113579-230962c8-33dd-4728-9430-4aae5cd8d4b7.png)

These days dark mode is increasingly becoming popular, so please try to add it.

For CSS these articles explain. Maybe these can be useful to implement in SCSS: 

https://dev.to/ananyaneogi/create-a-dark-light-mode-switch-with-css-variables-34l8

https://derekkedziora.com/blog/dark-mode-revisited

**Comment by SageofPHY6Paths** [comment]
It doesn't look all that complicated. Are there any problems with this feature? Like will the website become slow or something like that?

Also most websites are using a curved rectangular box as toggle. But to be consistent with this theme the toggle should probably be a rectangle with sharp edges. It should look like

⬜⬛

Maybe with a tick on whatever theme is currently active.

**Comment by SageofPHY6Paths** [comment]
Incase anyone knows how to do that please post here an example code. I know that [feeling-responsive/_sass/_01_settings_colors.scss](https://github.com/Phlow/feeling-responsive/blob/gh-pages/_sass/_01_settings_colors.scss)  is the file which contains the information related to colours.

**Comment by Phlow** [comment]
Hello @0lelouch – I am sorry, you have to try it yourself. Or you should ask a webdesign who can design it for you. Greetings, mo.

**Comment by SageofPHY6Paths** [comment]
@Phlow is there any chance that this project will upgrade from foundation version 5.5.0 to the current 6.7.3? I managed to get the dark mode toggle work. But often times the navbar dropdown is not working in dark mode and is giving an error.

That error was discussed here https://github.com/foundation/foundation-sites/issues/5486 and it was apparently resolved in foundation version 6 released on 2015

**Comment by SageofPHY6Paths** [comment]
After trying to manually upgrade foundation myself, I understood that it looks like very hard and lengthy process. So it might not be possible for you. Ok then, I am removing the dark mode toggle for now.
