### ISSUE TITLE
Weird bug on photos

### ISSUE THREAD

**Issue by felixinx** [Phlow/feeling-responsive#24]
Hi,

I just discoverd out a new bug. Maybe is a bad configuration (:

On [**https**://devinx.github.io/better-feeling-responsive/](https://devinx.github.io/better-feeling-responsive/) , I can click on the front image, and It will go to [**http**://devinx.github.io/better-feeling-responsive/](http://devinx.github.io/better-feeling-responsive/). if I click again on this image, it will go to [http://**phlow**.github.io/feeling-responsive/](http://phlow.github.io/feeling-responsive/)

So this is very weird...

Thanks

**Comment by TWiStErRob** [comment]
https://devinx.github.io/better-feeling-responsive/ is a GitHub pages 404

**Comment by felixinx** [comment]
Not for me...

**Comment by TWiStErRob** [comment]
There's a missing `n` in the target of the markdown link in your orignal post :)

**Comment by felixinx** [comment]
What post?
I used the default one, I only change the config file.

**Comment by TWiStErRob** [comment]
Ah, no, sorry, I mean in this issue. That's why I couldn't open it.

But after finding that out, I couldn't reproduce what you said was happening.

**Comment by felixinx** [comment]
Yes, it have been fixed. Maybe it's a cache issue.

Thank you very much for your time!
