### ISSUE TITLE
Navigation order in small view

### ISSUE THREAD

**Issue by niccokunzmann** [Phlow/feeling-responsive#241]
When I have a look at the page from a smartphone, I have the navigation in the wrong order - at least my perspective: The right items first, then the left items.

I saw that if I switch the navigation for left and right around in _navigation.html, everything is fine.
Now, I wonder: why would it be that the right items come first in the first place?
Would you like to receive a pull request?

https://github.com/kirstin/kirstinheidler.co.uk/commit/738f477852740bcb16d940d0f5c3341eff60ba16

**Comment by Phlow** [comment]
Hello @niccokunzmann you're right. Funny, that nobody mentioned that flaw till now. I also adjusted the Title/Icon for small devices which appeared to late. Thankyou!
