### ISSUE TITLE
Top menu bar disappearing after resizing window from large towards mobile (small)

### ISSUE THREAD

**Issue by valeriupredoi** [Phlow/feeling-responsive#243]
Hey guys, just wanted to start by thanking you lots for putting together an excellent template! You'd be happy to hear that we are using it to create the site of one of the largest scientific collaborations in Europe dealing with climate change science - check it out - currently in my home repo while we're developing it, but I'll move it to the organization's GH repo once we're done devving it:

- source: https://github.com/valeriupredoi/valeriupredoi.github.io
- site: https://valeriupredoi.github.io/

I have a very quick (and hopefully trivial) question for you: the site is losing the top bar with all the menu items (except Search, Privacy, and Contact) after a window resizing, and it stays like this until it gets to the `small` window size when the mobile-like menu and Home button appear: do you know how I can configure it so one doesn't lose that top bar when resizing, please? I am sorry to post what should be an html question, but I am a software engineer that knows very little html. Great many thanks in advance, and keep up the very good work! :beer: 

attn: my colleague site developer @SophieMacadamia

**Comment by Phlow** [comment]
I can't replicate your problem. In CSS there are breakpoints. They define when something should change in the design. You can adjust these changes yourself by modifying the theme.

But I ask myself: If someone opens your website. Why should he/she/it resize the window? I normally don't do it. And most of the websites are called from mobile devices where people can't change the screensize ;)

**Comment by valeriupredoi** [comment]
@Phlow cheers, mate! I have fixed it - the menu bar shows up immediately after a slight scroll after one has resized the window. Good point about the issue being about a corner case, being an engineer I am trying to find all possible use cases that might return a fault :grin: Cheers and keep up the good work :beer:
