### ISSUE TITLE
README: no installation instructions

### ISSUE THREAD

**Issue by iam-TJ** [Phlow/feeling-responsive#246]
As someone who's experimenting with Jekyll my first step was to explore possible themes. Most I've visited so far give simple installation instructions for those not yet familiar with the process or possible gotchyas.

It'd be nice to see the same in the README here.

**Comment by TWiStErRob** [comment]
The theme has the setup guide built in:
https://phlow.github.io/feeling-responsive/getting-started/

**Comment by Phlow** [comment]
@TWiStErRob Thankyou as always!

**Comment by iam-TJ** [comment]
I don't see it there. What I see is how to configure this theme with the assumption it is already installed.

I'm asking how do we go from this repository to having the theme installed locally? How do we integrate into an existing jekyll install without trampling on existing configuration - even superficial changes to `_config.yaml` such as `title:`  `host:` would be replaced if files are simply dropped in over the top from what I can tell ?

For newcomers to Ruby, Gems, and Jekyll none of these integration steps are obvious.

From what I've read the method for installing without trampling on existing files is to use a ruby Gem install via something like `echo "gem: jekyll-theme-feeling-responsive" >> Gemfile"; bundle` but that fails with:
```
$ bundle                                                                                                                                                                             
Fetching gem metadata from https://rubygems.org/...........                                              
Could not find gem 'jekyll-theme-feeling-responsive' in rubygems repository https://rubygems.org/ or installed locally. 
```
I thought that would work after reading about the introduction of `.gemspec` files and seeing this repository contains one.

**Comment by TWiStErRob** [comment]
Ah, that's because this "theme" was created before Jekyll themes were even concepts.
It's meant to be used the "old way": clone repo, change config, customize, add content, publish.

@Phlow I don't think you did package it as  theme, did you?

**Comment by Phlow** [comment]
@TWiStErRob You are right, I didn‘t package it as a theme.

1. Download the ZIP of the repository to your computer.
2. Unpack it. 
3. Open config.yaml and edit to taste.
4. Start Jekyll

**Comment by NALOMA** [comment]
I share the same feeling with the OP. 
I feel the getting started page should mention something about index,html or index.md that is trivial for experienced users but nontrivial for newbies. Most likely the theme is not a good starting point for newbies, however, it is seems really nice theme...
well, some time later probably...
