### ISSUE TITLE
Docker build fails due to ruby/listen gem incompatability

### ISSUE THREAD

**Issue by Ulfhednar-ASN** [Phlow/feeling-responsive#258]
While setting up a new project with Jekyll/Feeling Responsive, through forking the original repository, the _jekyll/builder_ docker container consistently fails to run, with the error code "_Error: Process completed with exit code 5_".

It appears the _listen-3.2.0_ gem is incompatible with ruby version _3.1.1p18_.

![image](https://github.com/Phlow/feeling-responsive/assets/93825995/9fab6c32-a0cb-4e0e-a4f3-bfed299cc64d)

**Comment by Phlow** [comment]
I have no idea how to help you. I don't use docker and it works fine with me. Maybe my theme is outdated?!?

**Comment by TWiStErRob** [comment]
Yes, @Phlow I think you need to do a `bundle update` to bump minors in the `Gemfile.lock` file which mandates 3.2.0, only from [3.3.0 it is compatible with Ruby 3](https://rubygems.org/gems/listen/versions/3.3.0).

@Ulfhednar-ASN you can do the same in your Dockerfile as a separate layer before `bundle install`-ing.

**Comment by Phlow** [comment]
Thankyou @TWiStErRob – I updated it. I get some errors according to sass but on my machine it works now.
