### ISSUE TITLE
How to use the theme with Jekyll

### ISSUE THREAD

**Issue by johann-petrak** [Phlow/feeling-responsive#259]
I am sorry if this is a newbie question but I was wondering how to actually use this theme with Jekyll?

I tried the following two approaches:

* specifying `gem "jekyll-theme-feeling-responsive"` in Gemfile to install and then using `theme: feeling-responsive` in `_config.yml` of my project, but this fails because the gem does not exist
* installing the "jekyll-remote-theme" gem as a jekyll plugin via the Gemfile (this worked) and then using `remote_theme: Phlow/feeling-responsive` in _config.yml to specify the theme but  that gave some errors and does not show the theme

Is there a description of how to make it work in a way where one just specifies the theme and overrides whatever one wants to change or reconfigure about it?

**Comment by johann-petrak** [comment]
I have now basically copied and modified the original files to make the site instead of specifying this as a theme, and I guess it is not really possible to use this as a theme where the user can switch between different themes easily?

**Comment by Phlow** [comment]
That's correct. It's an older theme, that doesn't offer the convenience. I am sorry for that.
