### ISSUE TITLE
Could not find a valid gem 'jekyll-theme-feeling-responsive'

### ISSUE THREAD

**Issue by MikeiLL** [Phlow/feeling-responsive#265]
Probably my mistake.

```
gem install jekyll-theme-feeling-responsive
ERROR:  Could not find a valid gem 'jekyll-theme-feeling-responsive' (>= 0) in any repository
```

It [looks like](https://github.com/Phlow/feeling-responsive/blob/db92e5e303aaea3c939f7c5aaad1354868143ee1/jekyll-theme-feeling-responsive.gemspec#L2) `jekyll-theme-feeling-responsive` is the correct name for this gem, but I seem to be missing something.

Also not finding it on https://rubygems.org.

Thanks. It's a nice theme!

**Comment by Phlow** [comment]
Hello @MikeiLL !

Glad you like this "old" theme.

A gem doesn't exist.

To use this theme, just download it. Use these instructions: https://phlow.github.io/feeling-responsive/getting-started/

Unfortunately I have no time to convert it into a gem.

Cheers, Moritz

**Comment by MikeiLL** [comment]
Thanks, man.
