### ISSUE TITLE
New Pages result in 404

### ISSUE THREAD

**Issue by marfi** [Phlow/feeling-responsive#28]
This is a great project, however I've tried creating additional pages, adding them to the pages folder, but when I navigate to them through the browser, they do not seem to exist and always result in 404.

I can add posts just fine.

Additionally, if I rename an existing page - again 404.

Any ideas?

**Comment by jjamor** [comment]
Rare ... I use pages under pages/ folder without problems.

In your fork, do you have a pages/info.md file? Is it generated as info/index.html ?

**Comment by marfi** [comment]
Yes, I have info.md and is generated fine.

I am actually working on it now:
https://marfi.github.io/feeling-responsive/info/

However if I rename it to about.md and then call https://marfi.github.io/feeling-responsive/about > 404.

**Comment by jjamor** [comment]
May be the "permalink" field in your *.md file?

**Comment by marfi** [comment]
Stupid me! It worked.

Thank you!

**Comment by Phlow** [comment]
Thank you Juan for helping out :)

**Comment by jjamor** [comment]
You're welcome! :smiley:
