### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by coconutcity30050** [Phlow/feeling-responsive#282]
Logging at level: debug Configuration file: /github/workspace/./_config.yml GitHub Pages: github-pages v232 GitHub Pages: jekyll v3.10.0 Theme: jekyll-theme-primer Theme source: /usr/local/bundle/gems/jekyll-theme-primer-0.6.0 Requiring: jekyll-github-metadata Requiring: jekyll-seo-tag Requiring: jekyll-gist Requiring: jekyll-paginate Requiring: jekyll-coffeescript Requiring: jekyll-commonmark-ghpages Requiring: jekyll-github-metadata Requiring: jekyll-relative-links Requiring: jekyll-optional-front-matter Requiring: jekyll-readme-index Requiring: jekyll-default-layout Requiring: jekyll-titles-from-headings GitHub Metadata: Initializing... Source: /github/workspace/. Destination: /github/workspace/./_site Incremental build: disabled. Enable with --incremental Generating... EntryFilter: excluded /Gemfile.lock EntryFilter: excluded /Gemfile EntryFilter: excluded /LICENSE EntryFilter: excluded /README.md Reading: _posts/design/2014-07-09-post-left-sidebar.md Reading: _posts/design/2014-07-10-breadcrumb.md Reading: _posts/design/2014-07-10-page.md Reading: _posts/design/2014-07-10-post-right-sidebar.md Reading: _posts/design/2014-08-19-page-fullwidth.md Reading: _posts/design/2014-09-10-portfolio.md Reading: _posts/design/2014-09-13-grid.md Reading: _posts/design/2014-09-14-video.md Reading: _posts/design/2014-09-15-gallery.md Reading: _posts/design/2014-10-08-header-image-pattern.md Reading: _posts/design/2014-10-09-header-full-width-image.md Reading: _posts/design/2014-10-09-header-image-color.md Reading: _posts/design/2014-10-09-header-logo-only.md Reading: _posts/design/2015-02-10-header-with-text.md Reading: _posts/design/2015-03-12-no-header-but-image.md Reading: _posts/design/2015-08-11-no-header.md Reading: _posts/design/2015-08-15-comments.md Reading: _posts/design/2015-08-16-typography.md Reading: _posts/design/2015-10-15-mediaelement_js.md Generating: JekyllOptionalFrontMatter::Generator finished in 0.000338591 seconds. Generating: JekyllReadmeIndex::Generator finished in 0.000114363 seconds. Generating: Jekyll::Paginate::Pagination finished in 0.002724761 seconds. Generating: JekyllRelativeLinks::Generator finished in 0.010725146 seconds. Generating: JekyllDefaultLayout::Generator finished in 0.000754837 seconds. Generating: JekyllTitlesFromHeadings::Generator finished in 5.4011e-05 seconds. Rendering: _posts/design/2014-07-09-post-left-sidebar.md Pre-Render Hooks: _posts/design/2014-07-09-post-left-sidebar.md Rendering Liquid: _posts/design/2014-07-09-post-left-sidebar.md Rendering Markup: _posts/design/2014-07-09-post-left-sidebar.md Requiring: kramdown-parser-gfm Rendering Layout: _posts/design/2014-07-09-post-left-sidebar.md Layout source: site Rendering: _posts/design/2014-07-10-breadcrumb.md Pre-Render Hooks: _posts/design/2014-07-10-breadcrumb.md Rendering Liquid: _posts/design/2014-07-10-breadcrumb.md Rendering Markup: _posts/design/2014-07-10-breadcrumb.md Rendering Layout: _posts/design/2014-07-10-breadcrumb.md Layout source: site Rendering: _posts/design/2014-07-10-page.md Pre-Render Hooks: _posts/design/2014-07-10-page.md Rendering Liquid: _posts/design/2014-07-10-page.md Rendering Markup: _posts/design/2014-07-10-page.md Rendering Layout: _posts/design/2014-07-10-page.md Layout source: site Rendering: _posts/design/2014-07-10-post-right-sidebar.md Pre-Render Hooks: _posts/design/2014-07-10-post-right-sidebar.md Rendering Liquid: _posts/design/2014-07-10-post-right-sidebar.md Rendering Markup: _posts/design/2014-07-10-post-right-sidebar.md Rendering Layout: _posts/design/2014-07-10-post-right-sidebar.md Layout source: site Rendering: _posts/design/2014-08-19-page-fullwidth.md Pre-Render Hooks: _posts/design/2014-08-19-page-fullwidth.md Rendering Liquid: _posts/design/2014-08-19-page-fullwidth.md Rendering Markup: _posts/design/2014-08-19-page-fullwidth.md Rendering Layout: _posts/design/2014-08-19-page-fullwidth.md Layout source: site Rendering: _posts/design/2014-09-10-portfolio.md Pre-Render Hooks: _posts/design/2014-09-10-portfolio.md Rendering Liquid: _posts/design/2014-09-10-portfolio.md Renderi

**Comment by coconutcity30050** [comment]
same bug as #267, 

To fix build error, the following lines are removed from assets/css/styles_feeling_responsive.scss

```
---
# Only the main Sass file needs front matter, rest is included from site.sass.sass_dir
sitemap:
  exclude: true
---
```

**Comment by TWiStErRob** [comment]
Have a read of the second half of this comment to understand what removing those lines mean:
https://github.com/Phlow/feeling-responsive/issues/267#issuecomment-1784804515
