### ISSUE TITLE
Please make it easier to reset the theme to a blank instance

### ISSUE THREAD

**Issue by armahillo** [Phlow/feeling-responsive#285]
The theme is really great, and you did very well with it. I also really love the demo instance you created, and how it shows all the various features and how to do things.

What I would really like is some way to have the theme in its barest-possible state -- no content (images or otherwise) from your theme demo, so that I don't accidentally leave something in and confuse my visitors.  The commented examples are helpful, and I would appreciate still having access to the demo version, but also some kind of pre-stripped version of the theme, or one that indicates how to safely strip out old files without removing files that are necessary for the theme to function. 

Thank you!

**Comment by Phlow** [comment]
I understand your wish. And thank you for your praise :)

If you like, you can do it. Just fork the repository, clean it up and send me the link. It's a lot of time. Just imagine how long it took me to realise the theme with collaborators.
