### ISSUE TITLE
Question about changing the content width

### ISSUE THREAD

**Issue by jlong8** [Phlow/feeling-responsive#34]
Hi all! Quick question: how do I change the content width for all pages? Can't seem to find it in the documentation. Thanks for your help!

**Comment by TWiStErRob** [comment]
The `.row` class is constraining the page size with `max-width` and that is coming from [_sass/foundation-components/_grid.scss](https://github.com/Phlow/feeling-responsive/blob/gh-pages/_sass/foundation-components/_grid.scss#L76); modify [_sass/_04_settings_global.scss](https://github.com/Phlow/feeling-responsive/blob/1d8fe4ae33e5245cb900e3b06668c6b4219a0ea7/_sass/_04_settings_global.scss#L89) to set the size:

```scss
$row-width: rem-calc(1000);
```

**Comment by Phlow** [comment]
Hey @jlong8!

*Feeling Responsive* is based on the [foundation framework](http://foundation.zurb.com/). Find out more about the Grid and how to use it via [Foundation Grid Doc](http://foundation.zurb.com/docs/components/grid.html)

@TWiStErRob pointed you already to the correct Sass-file. But be careful: If you are not so familiar with [Sass](http://sass-lang.com/), you can mess up your website.

But, have you seen [the full-width layout](https://phlow.github.io/feeling-responsive/design/page-fullwidth/) of *Feeling Responsive*? You can do a lot with all the space :)

All the Best, mo.


PS: @TWiStErRob Thanks again!
