### ISSUE TITLE
What is the workflow behind assets/js/javascript.min.js?

### ISSUE THREAD

**Issue by TWiStErRob** [Phlow/feeling-responsive#36]
How did you get from various JS library downloads to that minified file?

**Comment by Phlow** [comment]
I use a gulp task to do it... The Gulp file is not included... And also the original foundation files are not included. I wanted to keep it simple for users.

If you like, I can send you the whole package as a ZIP.

But I won't upload it on GitHub. This messes up the whole theme in my opinion.

**Comment by TWiStErRob** [comment]
Yes, please send it.

On a related note: shouldn't the font SVGs have a similar faith?

**Comment by Phlow** [comment]
The special icon font is build with http://fontcustom.com/ – a free tool.

You find all information and files needed in <https://github.com/Phlow/feeling-responsive/tree/gh-pages/assets/fonts> :)

**Comment by Phlow** [comment]
@TWiStErRob Did you get my package?

**Comment by TWiStErRob** [comment]
Yep, thanks very much.

**Comment by rah-phi** [comment]
hi phlow

could you please provide me with the js and gulp source files as well?

**Comment by Phlow** [comment]
What's your email address?

**Comment by rah-phi** [comment]
krah xiala net

thank you

**Comment by eksperimental** [comment]
Hi @Phlow, may I also have a copy of this? eksperimental [at] autistici [dot] org
thank you very much

**Comment by Phlow** [comment]
I've sent it. Will take a while to upload…

**Comment by eksperimental** [comment]
got it, thanks a lot!

**Comment by Phlow** [comment]
You're welcome :)
