### ISSUE TITLE
Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/styles_feeling_responsive.scss': Invalid US-ASCII character "\xE2" on line 1

### ISSUE THREAD

**Issue by brunoamaral** [Phlow/feeling-responsive#38]
This happened with ubuntu, with a fresh install of jekyll after running ```jekyll serve```

**Comment by Phlow** [comment]
Looks like a problem with the Sass-Compiler... Have you tried other themes? Did you encounter the same problem? If yes, it's a problem with your machine. If not, it might be specific with *Feeling Responsive*.

**Comment by manuelkiessling** [comment]
I've encountered the same issue when trying to `bundle exec jekyll serve` the freshly cloned _bare-bones-version_ branch on Mac OS X 10.11 with the following Bundler dependencies installed:
- bundler (1.10.6)
- colorator (0.1)
- ffi (1.9.10)
- jekyll (3.0.1)
- jekyll-paginate (1.1.0)
- jekyll-sass-converter (1.3.0)
- jekyll-watch (1.3.0)
- kramdown (1.9.0)
- liquid (3.0.6)
- listen (3.0.3)
- mercenary (0.3.5)
- rb-fsevent (0.9.6)
- rb-inotify (0.9.5)
- rouge (1.10.1)
- safe_yaml (1.0.4)
- sass (3.4.19)

Please see pull request #64 for a fix.

**Comment by TWiStErRob** [comment]
The cause is that 4 `scss` files:
- _01_settings_colors
- _02_settings_typography
- _06_typography
- _07_layout

contain two UTF-8 characters in comments:
- `–`: `â€“` (`E2 80 93`)
- `›`: `â€ş` (`E2 80 BA`)

which is totally fine, maybe there's some OS/ruby level default encoding that's different for @Phlow and you.

**Comment by manuelkiessling** [comment]
Wait, forget my pull request, it breaks SCSS processing. I'll dig deeper.

**Comment by manuelkiessling** [comment]
Added another commit to the pull request which fixes stuff for good.
