### ISSUE TITLE
Switching language

### ISSUE THREAD

**Issue by andrewvmail** [Phlow/feeling-responsive#40]
Is the language system meant for the users so that they can switch language? Tried to look for the switch language link but couldn't find it on the demo site.
Cheers!

**Comment by Phlow** [comment]
It's totally easy. *Feeling Responsive* always checks

<https://github.com/Phlow/feeling-responsive/blob/gh-pages/_data/language.yml>

If you want to translate your theme, just edit `language.yml`.

Even better:

1. Duplicate `language.yml`
2. Rename it to `language_language.yml`
3. Send me the file via merge request or through this comment-form.
4. I add it to the theme for future users.
5. Delete `language.yml`, rename your `language_language.yml` to  `language.yml`
6. Done :)

**Comment by TWiStErRob** [comment]
@Phlow I think he meant users of his website not users of the theme.

@andrewvmail You may be able to create a user/switcher but it means that you have to write a build script (losing GH-pages support) which switches out the `language.yml`, changes `site.baseurl` in `_config.yml` and builds the site for each language, copies it to an appropriate folder and you create the switcher yourself, maybe in navigation yml.
Or alternatively you can bake some strange JavaScript, but that feels hacky.

Ask yourself this: Does it really matter what languages the messages and navigation are if all my content has a fixed language? (Assuming you won't translate all your posts and pages to all languages.)

**Comment by andrewvmail** [comment]
That is right @TWiStErRob , 

I do mean for the user of the website. 

When you mean create a script what exactly I have to do? I'm not too familiar with how Jekyll works behind the scene. 
The language file you guys have is actually pretty good If I can hook into that functionality already and just build 2 version of the site that would work. 

Cheers
Andrew

**Comment by TWiStErRob** [comment]
something like below:
```bash
mv _data/language_de.yml _data/language.yml
bundle exec jekyll build --config _config.yml,_config_de.yml --destination _site/de
mv _data/language_en.yml _data/language.yml
bundle exec jekyll build --config _config.yml,_config_en.yml --destination _site/en
deploy _site # not a real command
```
and in `_config_<lang>.yml` set the `baseurl` to `'/en'` and `'/de'`; and have links to each "subsite" in `_data/navigation.yml`:

```yaml
- title: Language
  side: right
  dropdown:
  - title: English
    url: /en/
  - title: Deutsche
    url: /de/
```
Not tested, but should give you an idea of what I meant, good luck!

**Comment by andrewvmail** [comment]
OH I see! This looks like bash scripting  Thanks! @TWiStErRob 

Do i have this run in a hook with Jekyll perhaps? or i just run this as a shell script?

**Comment by TWiStErRob** [comment]
Yes, the simplest "build script" is a sequence of console commands in a "bash script" (or "batch file" on Windows). Jekyll is just like any other compiler. it grabs the source code of a site and produces some artifacts. How you call it is up to you. Maybe you should spend a few hours just reading through the [manual](http://jekyllrb.com/docs/home/), it's not that long.

**Comment by andrewvmail** [comment]
@TWiStErRob Great help will have to probably do that down the road. For now I think you hit the spot.

Thanks again

**Comment by flapperleenie** [comment]
I know this is a closed issue already, but I'm just wondering if anybody has tried to do the multilingual version, and if so if they could share an example? I'm a little stuck with the scripting...

**Comment by Phlow** [comment]
https://talk.jekyllrb.com/t/multi-language-strategies-with-jekyll/315

Have a look at this thread. There are multiple ways.

**Comment by teresacamachohull** [comment]
@flapperleenie maybe a little late, but i am using this jekyll plugin: [https://github.com/untra/polyglot](https://github.com/untra/polyglot) and so far it is working great with the feeling responsive theme.

**Comment by Phlow** [comment]
Thankyou for letting us know, @teresacamachohull
