### ISSUE TITLE
Overriding colors

### ISSUE THREAD

**Issue by andrewvmail** [Phlow/feeling-responsive#43]
Just wondering if the place to overrides the colors is scss/01_settings_colors.scss?
I tried to change things in there but color seems to not change...
I deleted the _site directory and do a rebuild without any success.
I think I'm missing a switch somewhere maybe?

Thanks

**Comment by andrewvmail** [comment]
Actually after digging a bit more some stuff is getting over ridden by things in _04_settings_global.scss

**Comment by TWiStErRob** [comment]
Yep, there are some rouge colors, but not much. Here's a re-colored example: http://www.twisterrob.net/blog/2015/06/Jekyll-hacks-for-development.html (source: https://github.com/TWiStErRob/twisterrob.github.io)
