### ISSUE TITLE
Theme is not visible

### ISSUE THREAD

**Issue by Molnfront** [Phlow/feeling-responsive#45]
Hi,

I forked your theme and changed the _config.yml to match my github page, but I get a error message: 

404

File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

It looks as if the index.html file is missing in the root folder. https://molnfront.github.io/

**Comment by Molnfront** [comment]
Hmm, it works from a subdir but not from the root. I just tried to rename the repository to: responsive and checked the adress http://molnfront.github.io/responsive/ and there it was.

What will the steps be to have it as the main site e.g http://molnfront.github.io?

**Comment by TWiStErRob** [comment]
There's a key difference between Phlow's hosting and your hosting, compare:
https://github.com/Phlow/feeling-responsive
VS
https://github.com/Molnfront/molnfront.github.io

There's a weird thing about personal GH-pages (`<username>.github.io` repos): they need a `master` branch, while any other projects needs a `gh-pages` branch to host a website.

So you need to merge `gh-pages` into `master` for it to work. I just went through this myself a week ago: https://github.com/TWiStErRob/twisterrob.github.io

**Comment by TWiStErRob** [comment]
You didn't need to rename it to `/responsive/` it's now live at http://molnfront.github.io/molnfront.github.io, that address just looks weird :)

**Comment by Molnfront** [comment]
Fixed!
Cloned, created new branch: master, synced. Changed repo namne to molnfront.github.io. Added a index.md file... Puh..

**Comment by Molnfront** [comment]
Tried to change the name of the index.md file att it still works, so my problem was that it was not in the master branch.

**Comment by Phlow** [comment]
@TWiStErRob Thank you for helping @Molnfront out... I have currently lot of things to do... My response is a little slow...
