### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Molnfront** [Phlow/feeling-responsive#46]
I built/run on my Mac using:  jekyll serve --config _config.yml,_config_dev.yml

And got a Error, then I removed the video and got this error: 
Error reading file /Users/jekyll/Documents/JekyllMolnfront/pages/pages-root-folder/index.md: (<unknown>): did not find expected key while parsing a block mapping at line 16 column 3 

It doesn´t  matter because I don't use that file. 

I saw that the build script creates a directory under _site. But in your configuration it is never used. Is there a simple way to make it not creating that dir?

**Comment by TWiStErRob** [comment]
This line looks garbled, make sure your frontmatter is valid YAML: https://github.com/Molnfront/molnfront.github.io/commit/2a2afc4bedbb48c34e317b79bd8c80ada8b0ed5d#diff-fc42fc94fad0c7d9167b451d9d487d10R19

**Comment by TWiStErRob** [comment]
@Molnfront Did you find out what was wrong?
