### ISSUE TITLE
Is there a "post" layout?

### ISSUE THREAD

**Issue by funkypenguin** [Phlow/feeling-responsive#5]
Hey,

Thanks for the excellent theme. I'm trying to get comfortable with it, and I note:

_config.yml seems to define pages vs posts. I imagine you might want to enable comments on posts but not pages:

```
defaults:
  -
    scope:
      path: "" 				# an empty string here means all files in the project
      type: "pages"
    values:
      show_meta: true 	# Show metadata beneath all pages
      # sidebar:    		# Possible values › left, right › by default there will be no sidebar
      comments: false
      author: "your_author_name"
  -
    scope:
      path: ""
      type: "posts"
    values:
      show_meta: true   # Show metadata beneath all posts
      # sidebar:        # Possible values › left, right › by default there will be no sidebar
      comments: true
      author: "your_author_name"
```

However, I don't seem to be able to use "layout: post" (jekyll just complains that it's an invalid layout), so thus far I'm just using "page" for everything. Is this the intended behaviour?

Thanks :)
D

**Comment by Phlow** [comment]
No there is no post layout. If you need one you can simply duplicate pages. But I decided to use just one layout with options via front matter.

Your snippet from the _config.yml just defines default-settings. And jekyll distinguishes between posts, pages and collection pages. For these pages you can define default. So for example 

~~~
 -
    scope:
      path: ""
      type: "posts"
    values:
      show_meta: true   # Show metadata beneath all posts
      # sidebar:        # Possible values › left, right › by default there will be no sidebar
      comments: true
      author: "your_author_name"
~~~

Here it is defined for all posts to set the front matter variable to `show_meta: true` – This will show categories, tags and a link to the blog archive underneath each post. But it uses the page-layout.

If you want to get rid of the error. Just duplicate the page-layout.
