### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by flapperleenie** [Phlow/feeling-responsive#54]
Is there an example/template for multilingual websites? There is a German language .yml in _data, and in the configuration you say that you can change the language. But how?
Also: it says the file is used in _includes/header, but that's not the case... 
If I understood correctly, this is language *support* but not really the basis for a multilingual website. Any help would be much appreciated :)

**Comment by TWiStErRob** [comment]
We discussed this in #40.
And remember this only translates some links like "more", your menu and content will have to translated as well somehow.

**Comment by flapperleenie** [comment]
thank you @TWiStErRob! I will try that and report back ;)
