### ISSUE TITLE
How can I set up the "Blog" page as my frontpage?

### ISSUE THREAD

**Issue by dmarcelinobr** [Phlow/feeling-responsive#57]
Hi, I want the Blog page be my homepage, how can I achieve this?

**Comment by TWiStErRob** [comment]
Copy `blog/index.html` to `pages/pages-root-folder` and add `permalink: /index.html` in frontmatter.
You should probably also remove `pages/pages-root-folder/index.md` or change its permalink to prevent clashes.

**Comment by dmarcelinobr** [comment]
I'm sorry, I can't see where frontmatter is. I receiving  a pagination error.

**Comment by Phlow** [comment]
Frontmatter is the upper information on each page... Have a look › http://jekyllrb.com/docs/frontmatter/

**Comment by TWiStErRob** [comment]
Re pagination check `config.yml`'s, and try to remove `blog/`

``` yml
paginate_path: "blog/page:num"
```

if it doesn't work, search Google for the error message.

**Comment by dmarcelinobr** [comment]
This is sort of embarrassing. I've the index.html in the `pages/pages-root-folder`
and  `paginate_path: "blog/page:num"`, but I getting `No such file or directory` error message, see below.  Nonetheless, the output works as desired, with the blog posts as the front page.

Here is how my `index.html` frontmatter looks like:

---

layout: blog
title: "Blog"
header: no

## permalink: "/index.html"

This is what I'm receiving: 

`Error reading file /Users/daniel/danielmarcelino.github.io/index.html: No such file or directory - /Users/daniel/danielmarcelino.github.io/index.html`
`Error reading file /Users/daniel/danielmarcelino.github.io/index.html: No such file or directory - /Users/daniel/danielmarcelino.github.io/index.html`

**Comment by TWiStErRob** [comment]
Did you remove `index.md` from `pages-root-folder`? Also I'm not sure how you formatted you comment above, but it looks like the `permalink:` line starts with `#` which, in yaml, means it's commented out. Try surrounding your code with ``` on separate lines, before and after the code block.

**Comment by FreeSlaver** [comment]
After doing what as you said, the home page is blog page, but there is no blog list.
