### ISSUE TITLE
bare-bones-version not up-to-date?

### ISSUE THREAD

**Issue by cjamin** [Phlow/feeling-responsive#61]
Hi,
It seems that the bare-bones-version is not up-to-date. For example, in _frontpage-widget.html, the way images are searched is not the same (it doesn't use "urlimg").
Or did I miss something?
Thanks!

**Comment by Phlow** [comment]
Oh, you're right. I have to update it. Currently I have not so much time. A little sloppy. Will do it soon.

**Comment by cjamin** [comment]
No problem, I just wanted to make sure it was "normal".

**Comment by kjhughes097** [comment]
Any idea when bare-bones-version will be update ?
Thanks.

**Comment by Phlow** [comment]
Currently I have no Time and I think I will delete the additional version. I am slowly working on a totally new version of *feeling responsive*
