### ISSUE TITLE
In index.md, the URLs don't have to be absolute, actually

### ISSUE THREAD

**Issue by cjamin** [Phlow/feeling-responsive#62]
This is more a "documentation" bug: in index.md (bare-bones version), it says that the URLs have to be absolute ("http://domain.de/must-be-absolut-url-like-this-one/"), but it's not true. And that's a very good thing! :)

**Comment by Phlow** [comment]
Thank you. Yes I made it possible both ways and forgot the documentation ;) I fixed it. With the next release the hint is gone.
