### ISSUE TITLE
html-proofer fails

### ISSUE THREAD

**Issue by sergiuszkierat** [Phlow/feeling-responsive#68]
Please try your impressive template with html-proofer. See the [Jekyll](http://jekyllrb.com/docs/continuous-integration/#the-test-script) docs.

A command :
`$bundle exec htmlproof ./_site --only-4xx --check-html --disable-external --allow-hash-href`
gives many failures :
`htmlproof 2.6.1 | Error:  HTML-Proofer found 603 failures!`

**Comment by Phlow** [comment]
hey @sergiuszkierat – I ran htmlproof and found some errors. but a lot of those errors were **no** errors. especially the `<img alt>`-errors. I don't understand the whole configuration of the program. But thank you for letting me know.
