### ISSUE TITLE
Facebook OG meta

### ISSUE THREAD

**Issue by rchampagneca** [Phlow/feeling-responsive#69]
I changed _includes/head.html from:

```
{% if page.image %}<meta property="og:image" content="{{ site.urlimg }}{{ page.image }}">{% endif %}

```

to:  

```
{% if page.image.thumb %}<meta property="og:image" content="{{ site.urlimg }}{{ page.image.thumb }}">{% endif %}
```

**Comment by Phlow** [comment]
I think, that is not a good idea: Have a look at what Facebook says:

https://developers.facebook.com/docs/sharing/best-practices#images

If your thumbs are bigger than 200x200 it is ok. But I would suggest, you always go with the bigger image on facebook. It will likely look better and generate hopefully more traffic to your website.

What do you think @rchampagneca ?

**Comment by TWiStErRob** [comment]
`page.image` is an object not an URL, see above navbar on https://phlow.github.io/feeling-responsive/design/typography/ (from #70)

**Comment by Phlow** [comment]
I solved the problem. Thankyou for letting me know. Haven't seen this one.

**Comment by Phlow** [comment]
Finally I saw it: {{ page.image.title }} solved the problem ;)

**Comment by Phlow** [comment]
I fixed the twitter image and facebook image – It's solved now. Thanks for point that out.
