### ISSUE TITLE
Theme preview incompatible with HTTPS

### ISSUE THREAD

**Issue by FloFra** [Phlow/feeling-responsive#7]
Your theme preview page does not support HTTPS. This can be fixed by using protocol relative url or even better the HTTPS based url by default in ```_config.yml```.

If users use "HTTPS everywhere" or similar plugins in their browser, this can lead to your demo not being displayed properly.

**Comment by Phlow** [comment]
This is something new to me: Should I change 

`url: "http://phlow.github.io/feeling-responsive"`

to

`url: "https://phlow.github.io/feeling-responsive"`

?

What happens, if somebody types in `http://phlow.github.io/feeling-responsive` – Will they be forwarded to **https**?

**Comment by Phlow** [comment]
Cool. I just tried it. It works. Thank you for letting me now!

This is especially cool, because [HTTPS as a ranking signal](http://googlewebmastercentral.blogspot.de/2014/08/https-as-ranking-signal.html)
