### ISSUE TITLE
Frontmatter tag in top page

### ISSUE THREAD

**Issue by shineon82** [Phlow/feeling-responsive#70]
in some posts appear tag of frontmatter, is this normal? Es: https://phlow.github.io/feeling-responsive/design/typography/

**Comment by shineon82** [comment]
There is also a problem with small screens 
![screenshot_2016-01-11-22-59-59](https://cloud.githubusercontent.com/assets/5788008/12248069/59cfcdfc-b8b7-11e5-8993-278d52995f53.png)

**Comment by TWiStErRob** [comment]
_Don't include two problems in one issue, that's always hard to handle._

The change proposed in #69 resolves the frontmatter issue.

**Comment by shineon82** [comment]
Ok, sorry! 

Thanks!

**Comment by Phlow** [comment]
It was my mistake. It should disappear now :)
