### ISSUE TITLE
Internet Explorer 11 - Word breaking 

### ISSUE THREAD

**Issue by rchampagneca** [Phlow/feeling-responsive#71]
While viewing **Feeeling Responsive** with Internet Explorer 11, I noticed some issues with word-breaking.

Using the IE development tools, I changed the **ms-word-break** and **word-break**  properties. Seemed to have corrected the issue. Is this worth pursuing as a fix ? 

![capture d ecran 2016-01-12 a 11 29 08](https://cloud.githubusercontent.com/assets/14007348/12277765/31689cce-b94b-11e5-9458-5aa2bcc819e7.png)

**Comment by Phlow** [comment]
I work on a Mac (Chrome, Firefox, Safari) – can you post the CSS-Code you use?

I see in the screenshot, that the right column there stands _…and start b_ and it breaks the word. Not a good thing. 

Is this the mistake screenshot or the final...

Do you know the soft hyphen `&shy`? [Check it out ›](https://en.wikipedia.org/wiki/Soft_hyphen)

**Comment by rchampagneca** [comment]
Here are the screen shots before and after:

## Before

![capture d ecran 2016-01-13 a 09 42 25](https://cloud.githubusercontent.com/assets/14007348/12297229/32816d0e-b9da-11e5-9b18-22b0a8898eaa.png)

## After

Changing **ms-word-break** property from **break-all** to empty. The property is defined in typography.scss (line 58).

![capture d ecran 2016-01-13 a 09 42 44](https://cloud.githubusercontent.com/assets/14007348/12297238/3cbb4e52-b9da-11e5-8b21-5ab9ed5900e1.png)

The attribute is described [here](https://msdn.microsoft.com/en-us/library/ms531184%28v=vs.85%29.aspx).

**Comment by rchampagneca** [comment]
I've done a little more research ... The **word-break** and **hyphen** properties require a **hyphenate-resource**. This resource is specified in the header using the **xmlns** tag  - For example, for a French language site:

```
<head>
<meta charset="utf-8">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="fr-FR">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```

Now, Internet Explorer properly displays the page with natural word breaks!

**Comment by Phlow** [comment]
Can you post the resources. I always go with HTML5 Boilertemplate. They don't use it. I would like to read more about it.

**Comment by rchampagneca** [comment]
I think the culprit are the properties of the `<p>` tag defined in **_06_typography.css**.

Both **-ms-word-break** and **word-break** are defined as **break-all**. According to this Microsoft [reference](https://msdn.microsoft.com/en-us/library/ms531184%28v=vs.85%29.aspx),
the **break-all** value will 

> break arbitrarily for non-CJK text (other than Chinese–Japanese–Korean). 

So, I've tested with the following changes to the stylesheet:

```
p {
    -webkit-hyphens: auto;
    -moz-hyphens: auto;
    -ms-hyphens: auto;
    hyphens: auto;
    -ms-word-break: normal;
    /* Non standard for webkit */
    word-break: normal;
}
```

I've been using the [Cross Browser Testing](https://crossbrowsertesting.com/) site to view pages under IE11. 

![windows 10](https://cloud.githubusercontent.com/assets/14007348/12379759/5c708ea4-bd2e-11e5-8c02-7ce39c5a56f0.png)

**Comment by Phlow** [comment]
Hey Roger! Thank you for being patient with me and sharing your knowledge. I adjusted the code to your suggestion. The `break-all`truly makes no sense.

**Comment by TheNaderio** [comment]
In case someone has the same problem with IE11 and the German language, the lang tag must **not** be set to `lang="de_DE"`, with only a simple `lang="de"` the IE is lucky.

**Comment by Phlow** [comment]
Thankyou @TheNaderio
