### ISSUE TITLE
(Not issue) Topbar menu items order

### ISSUE THREAD

**Issue by shineon82** [Phlow/feeling-responsive#72]
Can I change the order of the menu items in the top bar? 
Browsing from mobile layout they are in alphabetical order.

Thank you!

**Comment by rchampagneca** [comment]
On a mobile device the hamburger menu will first display the **right navigation** menu items followed by the **left navigation** menu items as illustrated below - I don't see how they can be ordered alphabetically.

![capture d ecran 2016-01-12 a 19 50 46](https://cloud.githubusercontent.com/assets/14007348/12281786/06375fe2-b967-11e5-8f93-e2d00aebc0df.png)

**Comment by shineon82** [comment]
Oops, sorry!

Coincidentally my menu is in alphabetical order if I display the right items first.
