### ISSUE TITLE
Problems with jekyll-gist dependency

### ISSUE THREAD

**Issue by fedorov** [Phlow/feeling-responsive#73]
When I am trying to do 'jekyll serve', I have the error below:

```
/Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:30:in `require': cannot load such file -- jekyll-gist (LoadError)
```

The dependency is installed:

```
$ gem list jekyll-gist

*** LOCAL GEMS ***

jekyll-gist (1.4.0)
```

Any suggestions why I have the problem?

**Comment by fedorov** [comment]
Removed Gemfile.lock, ran `bundle install` - problem solved. Sorry for the noise.

**Comment by Phlow** [comment]
No problem @fedorov :) I ran into a similiar problem and couldn't figure it out at first. Took me some time.

**Comment by TWiStErRob** [comment]
Same here, I just ran into this and found this one quickly, thanks for sharing the solution.
