### ISSUE TITLE
Opened DIV in Footer.html

### ISSUE THREAD

**Issue by rchampagneca** [Phlow/feeling-responsive#75]
I believe that the id="footer" div in _Footer.html ...

```
  <footer id="footer-content" class="bg-grau">
    <div id="footer">
      <div class="row">
```

should be closed as follows:

```
    </div><!-- /#subfooter -->
  </div> <!-- id=footer -->
</footer>
```

Regards,
Roger.

**Comment by Phlow** [comment]
I don't think so… I folded the __footer.html_ It looks good. 

![collapse](https://cloud.githubusercontent.com/assets/2551270/12415537/83f6ac00-be9c-11e5-8fa9-dc8a9e54f50c.png)
