### ISSUE TITLE
Google+ social media icon is missing

### ISSUE THREAD

**Issue by fedorov** [Phlow/feeling-responsive#76]
Would be great to have google+ icon support here:

![image](https://cloud.githubusercontent.com/assets/313942/12430226/81e50126-bebc-11e5-96fd-b841d7cc54af.png)

For the reference, that icon is available from http://entypo.com/. If this is something simple, and the process of adding it is somewhere described, let me know - I can look into this myself.

**Comment by Phlow** [comment]
Hey @fedorov – To built the custom font I used https://github.com/FontCustom/fontcustom/

All you need is available in this folder https://github.com/Phlow/feeling-responsive/tree/gh-pages/assets/fonts

Just throw your svg-file into _svg-files-for-custom-font/_ and let the tool do the rest.

It should be not so hard to do it :)

**Comment by fedorov** [comment]
Thanks, this helps! Let me see if I can figure this out.

**Comment by fedorov** [comment]
Hmm. Not sure why this was closed. If I can figure it out, I will follow up with a pull request. If not, I would think this issue is important enough to be be open until resolved. Regarding figuring this out on my own, I don't use brew on my mac (I use macport), so installing fontcustom is not straightforward, unfortunately.

**Comment by TWiStErRob** [comment]
I did the same, I wanted more icons and I needed to generate my own font. I did it on Windows though, but it was fairly straighforward.

If @Phlow includes a Google+ icon, he could include all of the others from Entypo. @fedorov where would you draw the line to include or not? I agree though, Google+ is big enough that it should be in.

**Comment by Phlow** [comment]
hey @fedorov and @TWiStErRob 

I made the custom font to keep it small and only choose icons, I thought were needed. Thanks to @fedorov Google Plus is now in the mix. I wasn't aware, that people like to use it.

Thank you @fedorov for taking your time to check it out, how it works :) I merged your pull request.

**Comment by fedorov** [comment]
@Phlow you are welcome, I am happy I could help. It was super easy with the instructions you gave me, the most difficult part was installing fontcustom (I had to do it on a linux machine!).

**Comment by fedorov** [comment]
To my deep regret, the icon does not show up when I try to use it in my configuration ... :(

As I was investigating what is different, I noticed that it seemed like _sass/_06_typography.scss needed to have icon-googleplus mentioned (I do not know anything about this file, just was comparing where icon-twitter was showing up), but editing this file didn't help. Any ideas what else might be missing?

This is how it shows up now, empty space is where google+ icon was supposed to render...

![image](https://cloud.githubusercontent.com/assets/313942/12498163/7da8747c-c06e-11e5-9ed2-8bfb44eb5cfc.png)

I am not going to investigate this further, because I am not at all familiar with the underlying technologies, and the issue is not so important. But if this is something obvious to you @Phlow or @TWiStErRob please let me know what I am missing!

**Comment by TWiStErRob** [comment]
The class is applied to the element from the _data file, but because the scss file is missing the class declaration the `:before` is not giving it the right content.

`assets/font/iconfont.css` is not referenced in any HTML file, it must be copied to the end of the typo file you mentioned. Apply the [same patch](https://github.com/Phlow/feeling-responsive/pull/77/files#diff-10feb82b67926023fca6142f5905948c) to the scss file too.

**Comment by fedorov** [comment]
@TWiStErRob, as I mentioned, I did modify _sass/_06_typography.scss, this is what I did:

```
diff --git a/_sass/_06_typography.scss b/_sass/_06_typography.scss
index 9a60e11..5df1b39 100644
--- a/_sass/_06_typography.scss
+++ b/_sass/_06_typography.scss
@@ -398,6 +398,7 @@ mark {
 .icon-feather:before,
 .icon-github:before,
 .icon-globe:before,
+.icon-googleplus:before,
 .icon-heart:before,
 .icon-heart-outlined:before,
 .icon-home:before,
@@ -466,6 +467,7 @@ font-smoothing: antialiased;
 .icon-feather:before { content: "\f114"; }
 .icon-github:before { content: "\f115"; }
 .icon-globe:before { content: "\f116"; }
+.icon-googleplus:before { content: "\f136"; }
 .icon-heart:before { content: "\f117"; }
 .icon-heart-outlined:before { content: "\f118"; }
 .icon-home:before { content: "\f119"; }
```

This didn't help.

I didn't quite understand - what else did you suggest I should do?

**Comment by fedorov** [comment]
See the branch above. I realized the actual svg file for the icon was missing - I only committed the modified files! - in addition to the _sass/_06_typography.scss not modified, so I fixed those issues, but something is still missing. I found related commit in #9 that added icon for Xing, but did not find what is wrong with mine...

**Comment by Phlow** [comment]
Hey @fedorov 

I think we are finally there: I added G+ on the site http://phlow.github.io/feeling-responsive/ to see, if it is showing up.

I had to add the class to __sass/_06_typography.scss_

And then you have to use it in __data/socialmedia.yml_

Check the commit, if you like to figure out what went wrong.

It's quite complex sometimes, I know.

But I hope you're happy with the result :)

**Comment by fedorov** [comment]
Thank you @Phlow! I thought I did the same changes when I was debugging this yesterday, but it didn't work for me. It indeed works now. Thanks!
