### ISSUE TITLE
Nav buttons at bottom of blog posts mesh together

### ISSUE THREAD

**Issue by mobilesuitguy** [Phlow/feeling-responsive#91]
https://phlow.github.io/feeling-responsive/design/no-header/
^ Example there

Fantastic theme by the way. Just a minor issue with the nav buttons at the bottom of blog posts. When viewed past a certain width of screen like with a regular sized smartphone, the buttons mesh on top of each other (middle and right buttons). Not sure if this is where I would go to post issues since it's my first time doing so on GitHub, sorry if it is not the right place. I'm having a great time learning Jekyll with your blog, thank you!

**Comment by TWiStErRob** [comment]
I had the same problem. I solved it like this: https://github.com/TWiStErRob/twisterrob.github.io/commit/161c20537744b9d28d4962e04bdf9bbae47a895d#diff-3f83e865daa541c7370132a69f1d5c87

See it live at http://design.google.com/resizer/#device=handset&url=http%3A%2F%2Fwww.twisterrob.net%2Fblog%2F2015%2F06%2FJekyll-hacks-for-development.html&width=360

**Comment by mobilesuitguy** [comment]
Thanks @TWiStErRob, that should do it! I was looking into it myself and I guess 'small' doesn't stack the buttons when the screen is reduced. I'm digging some of the stuff you included on your website by the way!

**Comment by TWiStErRob** [comment]
Don't close the issue, it still exists in feeling-responsive.
If you leave it open it'll remind @Phlow to take action...
(including the possibility of explicitly ignoring it by closing).

**Comment by mobilesuitguy** [comment]
I see, thank you for helping me learn the ropes around here.

**Comment by Phlow** [comment]
Finished.
