### ISSUE TITLE
Embedding FontAwesome Icons in Text

### ISSUE THREAD

**Issue by SZanlongo** [Phlow/feeling-responsive#93]
Hey there! I've been playing around with feeling-responsive and it looks perfect for my needs.

I'd like to replace images with FontAwesome icons (or Entypo like you are already using). For example on index.md, replace the images with some appropriate icon. Does feeling-responsive support this functionality?

**Comment by TWiStErRob** [comment]
Do you mean like this?
![image](https://cloud.githubusercontent.com/assets/2906988/14799326/3ae5e520-0b3c-11e6-960f-e50f3e86d20d.png)

All I did (in Chrome Developer Tools) is:
- remove the `<img>` from the `frontpage-widget`: ![image](https://cloud.githubusercontent.com/assets/2906988/14799422/adfb7408-0b3c-11e6-8674-6c017c0b5268.png)
- add `class="iconfont icon-home"`: ![image](https://cloud.githubusercontent.com/assets/2906988/14799397/8e35ede2-0b3c-11e6-9756-a5727faf993c.png)
- add a new CSS style to increase the size of the "icon":
  
  ``` css
  .frontpage-widget > a.iconfont:before {
      text-align: center;
      width: 100%;
      font-size: 150px;
  }
  ```

List of available icons can be found at the end of `_sass/_06_typography.scss`, which may not include what you want, in that case see #76. To edit the layout: edit `index.md`'s frontmatter to configure the widgets, e.g. add something like `icon: 'home'` to each widget; and modify the file `_includes/_frontpage-widget.html` like so:

``` django
<a href="{{ widget_url }}" class="iconfont icon-{{include.widget.icon}}">
```

**Comment by SZanlongo** [comment]
That's exactly it! Where do you recommend I place the new css style?

**Comment by TWiStErRob** [comment]
When I made a pull for this repo I put [similar code](https://github.com/Phlow/feeling-responsive/commit/ebe7cebcc4056e8e2a64e24160b970f35d13fa4f#diff-ae1f89224ec15341bd4585709d534f96R147) in `09_elements`, but it was justifiably removed later following the KISS principle.

**Comment by SZanlongo** [comment]
Ah, that works.

My last question: I'm trying to add FontAwesome, and went ahead and copied all of its files to their corresponding scss, fonts, css folders. I've also added it to _06_typography.scss (I think this is how it should be):

> @font-face {
>   font-family: 'iconfont';
>   src: url('../fonts/iconfont.eot'); /\* IE9 Compat Modes _/
>   src: url('../fonts/iconfont.eot?#iefix') format('embedded-opentype'), /_ IE6-IE8 _/
>        url('../fonts/iconfont.woff') format('woff'), /_ Pretty Modern Browsers _/
>        url('../fonts/iconfont.ttf')  format('truetype'), /_ Safari, Android, iOS _/
>        url('../fonts/iconfont.svg#svgFontName') format('svg'), /_ Legacy iOS */
>        url('../fonts/fontawesome-webfont.svg') format('svg');
> }

Is this the correct way to add it, and how would I use the fonts once they're set up?

**Comment by TWiStErRob** [comment]
I think you'd need another `@font-face` declaration, because you're mixing different fonts. The glyphs may get confused and also it looks like your missing formats/fallbacks. The usage is according to their documentation, usually through a class that references the font-family, though I'm not that experienced with web fonts.

**Comment by SZanlongo** [comment]
I’ve copied the FA `scss` and `font` folders to mine, and updated `styles_feeling_responsive.scss` with `@import "font-awesome/font-awesome";`, however I still can’t get FA fonts to show up. I’d appreciate any help you can provide if you have the time, or close this if its not relevant.

**Comment by TWiStErRob** [comment]
You should be a little more specific/precise, with the web paths matter, a lot (e.g. there's no `font` folder in the FA that I found). I tried the following and it worked for me, compare this to what you did and you should find what you missed:
1. Download from https://fortawesome.github.io/Font-Awesome/ > "No thanks, just download"
2. Extract `font-awesome-4.6.1.zip/font-awesome-4.6.1/fonts/*.*` to `<website>/assets/fonts/*.*`
3. Extract `font-awesome-4.6.1.zip/font-awesome-4.6.1/scss/*.*` to `<website>/_sass/font-awesome/*.*`
4. Added to `<website>/assets/css/styles_feeling_responsive.scss`:
   
   ``` scss
   @import "font-awesome/font-awesome.scss"
   ```
5. Edited an HTML file in the project by adding (from [examples](https://fortawesome.github.io/Font-Awesome/examples/)):
   
   ``` html
   <i class="fa fa-camera-retro fa-5x"></i> fa-5x
   ```

The result was:
![image](https://cloud.githubusercontent.com/assets/2906988/14970665/36d41ad0-10cb-11e6-8edb-43d13086696f.png)

**Comment by SZanlongo** [comment]
Ah, gotcha. I've done all of the above; my problem is trying to embed icons inline in the markdown pages.

**Comment by TWiStErRob** [comment]
This usage is inline: "fa-5x" is text, I just used a big font. The above could be in markdown too, because most markdown processors don't process HTML code, just output it as-is.

**Comment by SZanlongo** [comment]
Hmm, I'm sure it's something trivial, but I can't get it to work. After doing the above, I went into `index.md` and changed the first widget as follows:

`text: 'Every <i class="fa fa-camera-retro fa-5x"></i> fa-5x good portfolio website has a blog with fresh news, thoughts and develop&shy;ments of your activities. <em>Feeling Responsive</em> offers you a fully functional blog with an archive page to give readers a quick overview of all your posts.'`

just to test. However, nothing happens:

![example](https://i.imgur.com/zVTLFIs.png)

**Comment by TWiStErRob** [comment]
That `text` is rendered like this: `<p>{{ include.widget.text }}</p>` in `_includes/frontpage-widget.html`.
Check your rendered output in Chrome Developer Tools Inspector, that should be highlighted like the other tags. If that's correct then check the Styles to see if they're correctly defined. Then check the Console and Network tabs for HTTP 404s, maybe your font's are incorrectly linked. Do you have this site published?

**Comment by SZanlongo** [comment]
I have `<p>{{ include.widget.text }}</p>` in my `_includes/frontpage-widget.html`. I've been running Jekyll on my localhost, but the (minor) changes I've made can be found [here](https://github.com/SZanlongo/feeling-responsive/commit/11942f48d3ee67c77132ac6a1a789206fd7aafa7).

**Comment by TWiStErRob** [comment]
You likely didn't check the console tab in dev tools:

> Font from origin 'http://localhost:4000' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:4000' is therefore not allowed access.

If you change the url you're looking at from http://127.0.0.1:4000 to [http://localhost:4000](http://localhost:4000) it'll magically work. This likely happens because even though you open `127.0.0.1`, Chrome then loads [http://localhost:4000/assets/css/styles_feeling_responsive.css](http://localhost:4000/assets/css/styles_feeling_responsive.css) and `@font-face { font-family: 'FontAwesome'; src: url("../fonts/fontawesome-webfont.eot?v=4.6.1");` will be relative to that file whose host is `localhost`.

**Comment by TWiStErRob** [comment]
If you really want to look at the site through `127.0.0.1` change `_config_dev.yml` to:

``` yml
url:        'http://127.0.0.1:4000'
urlimg:     'http://127.0.0.1:4000/images/'
```

**Comment by SZanlongo** [comment]
Oh wow; that takes care of it! I was missing the `--config _config.yml,_config_dev.yml` flags...

I suppose I'll ask another question and wrap it up: I'd like to use the FA icons in the widgets (as in your first comment) rather than the native Entypo icons. I suppose I could add all of the corresponding svg files as in [#76](https://github.com/Phlow/feeling-responsive/issues/76), but would like to check if there is a more elegant way than adding all of that overhead.

**Comment by TWiStErRob** [comment]
From a user's perspective a custom font with least possible glyphs or a cdn-served widely used font is the best solution. These give the fastest download speed/highest possibility of cache hit.

You'll need to recompile with fontcustom, but it's not that hard, and you'll only need to do it once while you set up your site; or you can ditch entypo/fontcustom and go for full FA, all you need to change is the class in the widget include and replace every other fontcustom usage (in styles, _data, html files) with the corresponding FA icon, then get rid of that font. Note that going FA you'll be restricted to only FA icons. The key of using a self-compiled font is that you can cherry pick even from different sources.

**Comment by Phlow** [comment]
I think in the future I will get rid of the custom font and use SVGs. It's easier to understand and if you put them directly in the HTML it won't blow up the code very much. Can I close this thread as solved?

**Comment by TWiStErRob** [comment]
I don't think that's a good idea, is SVG's penetration big enough to not use custom fonts? I think custom fonts have a lot of benefits including: styling as color/bold/slanted without needing to change the svg source or JS code, performance (a lot of things are precalculated in the font file).
(I think it can be closed, we've deviated enough from the original question)

**Comment by Phlow** [comment]
OK. I close it. If you are interested, have a look at https://github.com/Phlow/simplicity There I use SVGs in HTML – And you can animate SVGs and style even the colors via CSS.
