### ISSUE TITLE
upgrading to foundation 6.2.1

### ISSUE THREAD

**Issue by george-githinji** [Phlow/feeling-responsive#94]
Sorry if this sounds obvious. How do you upgrade the foundation assets and to the latest versions?

**Comment by Phlow** [comment]
I haven't done it. I think this is not so trivial. It's on my personal wishlist but I have not the time to make the change to Foundation 6

**Comment by biorelated** [comment]
OK @Phlow. Would you be be able to outline the pain points? I would be happy to help.
