### ISSUE TITLE
Templates, click on Typography, got HTTP 404

### ISSUE THREAD

**Issue by time4testing** [Phlow/feeling-responsive#95]
There is a missing page, when click on Templates, Typography, got error message HTTP 404, not found.  file apparently got lost from the template.  Please correct and add it for the benefit of anyone who uses your template.  Thank you.

**Comment by TWiStErRob** [comment]
Huh, for some reason https://github.com/Phlow/feeling-responsive/blob/gh-pages/_posts/design/2015-08-16-typography.md is rendered as https://phlow.github.io/feeling-responsive/design/typography/typography/... there should be only one typography in the path. (I got this from blog archive where it has the correct link.)

**Comment by Phlow** [comment]
I figured it out: In front matter of »Wonderful Typography« the post has two categories: design and typography. Thanks to the __config.yml_-settings the rendered path is _https://phlow.github.io/feeling-responsive/design/typography/typography/_ – I corrected it in the navigation. Thanks for telling us.
