### ISSUE TITLE
consider speed optimizations - JS/CSS above the fold and caching

### ISSUE THREAD

**Issue by fedorov** [Phlow/feeling-responsive#96]
would be great to get the template more ... responsive!

see below results from https://testmysite.thinkwithgoogle.com/

![image](https://cloud.githubusercontent.com/assets/313942/15953336/dca16866-2e97-11e6-8480-d37c404ceea8.png)

![image](https://cloud.githubusercontent.com/assets/313942/15963302/d8148106-2ede-11e6-83a1-f542f5c97572.png)

**Comment by Phlow** [comment]
You can always improve. I test mostly with GTMetrix and Pingdom Tools – Do you have any suggestion how we can speed up the site?

![bildschirmfoto 2016-06-13 um 16 13 29](https://cloud.githubusercontent.com/assets/2551270/16010507/ce854922-3181-11e6-88ea-23e175cd15b1.png)
![bildschirmfoto 2016-06-13 um 16 13 12](https://cloud.githubusercontent.com/assets/2551270/16010508/ce8af692-3181-11e6-8644-be839e8c2238.png)

**Comment by fedorov** [comment]
@Phlow I am really just a grateful user of your platform. I have close to zero experience in web development (as you can see from the repositories I contribute to under my account!).  If I manage to figure out improvements implementation, I will definitely submit a patch. 

Looking at the recommendations from google, it looks like "Eliminate render-blocking JavaScript and CSS in above-the-fold content" is the one they recommend as absolutely necessary. Is this something that can be handled in the template? I think this is a general JS development rule, from the very little I know about JS development...

**Comment by Phlow** [comment]
@fedorov No need to apologize :) – It's always difficult to eliminate all Javascript in the header section. This theme uses/needs quiet a lot of Javascript. If it's to slow for you, try my other theme called [Simplicity](http://phlow.github.io/simplicity/). It uses no Javascript at all, yet has that _Eliminate render-blocking JavaScript and CSS in above-the-fold content_ – But is uses no Javascript and all the pages are really small › the size of a page with its images is the most important thing for a website.

## Results for _Simplicity_

![bildschirmfoto 2016-06-14 um 17 49 41](https://cloud.githubusercontent.com/assets/2551270/16049570/7d0d5ec2-3258-11e6-88a8-88e3dde0a955.png)
![bildschirmfoto 2016-06-14 um 17 50 03](https://cloud.githubusercontent.com/assets/2551270/16049571/7d11af72-3258-11e6-8ac7-361581de27b8.png)

**Comment by ghost** [comment]
If you guys need to hit PageSpeed 100 with a Jekyll site I've created a free and open source tutorial for you using a different theme as an example here: https://habd.as/pagespeed-100-with-jekyll-s3-and-cloudfront/

Base themes should be GH-pages compatible in most cases for wider adoption.

**Comment by sugardayfox** [comment]
Or you can wrap your JS (usually the culprit) in this script as a simple lazyload trick:

window. addEventListener('scroll',() =>
  set Timeout(() => {
   // load Intercom and other JS here 
     }, 1000),
  { once: true }
);

Here's how it looks:
![lighthouse3](https://user-images.githubusercontent.com/1508705/75976531-870ada80-5ed2-11ea-8ae5-3f56701b3208.png)

Taken from here: https://marketingexamples.com/seo/performance
