### ISSUE TITLE
Can't get image to show on frontage.html

### ISSUE THREAD

**Issue by ghost** [Phlow/feeling-responsive#97]
I can get a logo to show up on the front page, but for the life of me I can't get a background image to show up.  I've tried various things in the front matter of frontpage.html but can't get an image to do what your image is doing on your front page.

What I want is for #masthead to end up with the following:
background-color: #000; background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('/assets/img/Frontpage.png');

**Comment by TWiStErRob** [comment]
If an image doesn't load always check the network tab of your browser's developer tools as you may be referencing it incorrectly and getting a 404.

The main page logo is put there with [backstretch](https://github.com/Phlow/feeling-responsive/blob/ca50d9ef9fc5b38b9e9626fda93901131d74a9c8/_includes/_footer_scripts.html#L13) using an `<img src`, see [_masthead](https://github.com/Phlow/feeling-responsive/blob/gh-pages/_includes/_masthead.html#L55). The [styles for `#masthead`](https://github.com/Phlow/feeling-responsive/blob/ca50d9ef9fc5b38b9e9626fda93901131d74a9c8/_sass/_07_layout.scss#L64) are generated from scss. I think you'll have to modify these places to get what you want, the current implementation only allows you to change the `src` of the `<img>`.

Hope this helps.

**Comment by ghost** [comment]
The problem is that I've overridden the styles for masthead and it's still got the wrong information.  I have a suspicion that front page doesn't read the right settings.  In _masthead there's ways to get what I need but they don't seem to work with any settings.  I need to know how the front page of the example github.io page is generated.

**Comment by ghost** [comment]
Also, if I hack the code in the inspector or manually modify the file in _site it looks great.  The problem is that I've got no way to override the css for the #masthead object that "sticks"

**Comment by TWiStErRob** [comment]
Did you start Jekyll in watch mode? Or regenerate the site after you modified the styles?

**Comment by ghost** [comment]
## It was compiled from scratch.  I've also got a page in _pages with the following:

id: 835
title: Schedule
layout: single
header:
  image_fullwidth:'Frontpage.png'
permalink: /schedule/
tc-thumb-fld:
- 'a:2:{s:9:"_thumb_id";i:841;s:11:"_thumb_type";s:10:"attachment";}'
  post_slider_check_key:

##   - 0

... and that one doesn't work either.

**Comment by TWiStErRob** [comment]
Check your browser's developer tools for missing resource errors.

(Tip: on Github you can format code by surround it with <code>```</code>, see [help](https://guides.github.com/features/mastering-markdown/) for more.)

**Comment by ghost** [comment]
It's not missing. It's not in the markup. The backstretch isn't getting triggered.  My markup may be wrong, but for whatever reason I'm just not getting the markup to be correct.

The style for masthead is:
position: relative; z-index: 0; background-image: none; background-position: initial initial; background-repeat: initial initial;

My attempt to override this in the css files is overridden by something else setting the above attributes, but for the life of me I can't figure out where it is - z-index isn't set for masthead anywhere.

**Comment by ghost** [comment]
I got it, thank you!

K
