### ISSUE TITLE
google_analytics_tracking_id not disabled in dev mode

### ISSUE THREAD

**Issue by yafred** [Phlow/feeling-responsive#99]
Hi,

I noticed that using _config_dev.yml does not disable google analytics.

Workaround: to properly disable analytics, google_analytics_tracking_id must be set to false (not left empty).

```
# Disable when not in production
google_analytics_tracking_id: false
```

Thanks for the theme

**Comment by TWiStErRob** [comment]
Huh, that's interesting, I have the empty value and it doesn't include ga code in footer_scripts.
It is possible that the `_config_dev.yml` is missing a new line at the end of the file.

Just to double-check: were you running `jekyll serve` with the correct `--config` switch?

**Comment by yafred** [comment]
That is strange.

I make a  copy/paste of the command described in _config_dev.yml.
As for the file, I just downloaded and unzip the git repo (so no modification).

When I saw the problem, I changed the tracking id to x (letter x) and it did change the value in the html produced.

It's running on windows.

**Comment by TWiStErRob** [comment]
I'm running Windows too. Try `gem install bundler`, `bundle install` and `bundle exec jekyll ...`. Maybe running a raw `jekyll ...` is a different version.

**Comment by TWiStErRob** [comment]
> I changed the tracking id to x (letter x) and it did change the value in the html produced.

Just remembered: when you change a config value you have to restart `serve`, and maybe even need a non-incremental generation.

**Comment by TWiStErRob** [comment]
I just tried again and you're right, the empty value is not picked up, it needs to be `false`. I think this is because of Jekyll 3, it seems I may have had some stale `_site`. You should create PR from your repo.
